"use client"

/**
 * AI Templates Section
 * @description Unified AI template section that merges hardcoded templates from
 * AI_TEMPLATE_CATEGORIES with dynamically generated templates from the database.
 * All templates are grouped by their actual category (e.g. "Engagement", "Personal Story")
 * so users see a single, consistent view per category.
 * @module components/features/template-library/ai-templates-section
 */

import * as React from "react"
import { IconSparkles } from "@tabler/icons-react"

import { cn } from "@/lib/utils"
import { Badge } from "@/components/ui/badge"

import { AI_TEMPLATE_CATEGORIES, getCategoryColor } from "./constants"
import { AITemplateCard } from "./ai-template-card"
import type { AITemplate, Template } from "./types"

/**
 * A unified AI category for display: merges hardcoded + DB templates
 */
interface UnifiedAICategory {
  /** Unique identifier based on category name */
  id: string
  /** Category display name */
  name: string
  /** Icon element */
  icon: React.ReactNode
  /** Color class for the icon badge */
  color: string
  /** Border accent color class */
  borderColor: string
  /** All AI templates in this category (hardcoded + dynamic) */
  templates: AITemplate[]
}

/**
 * Props for the AITemplatesSection component
 */
interface AITemplatesSectionProps {
  /** Callback when using an AI template to create a post */
  onUseAITemplate: (template: AITemplate) => void
  /** Callback when saving an AI template to the user's library */
  onSaveAITemplate: (template: AITemplate) => void
  /** AI-generated templates from the database (auto-generated by the cron) */
  dynamicTemplates?: Template[]
}

/**
 * Builds unified categories by merging hardcoded AI templates with DB-generated ones.
 * Groups everything by the actual template category field.
 *
 * @param dynamicTemplates - AI-generated templates from the database
 * @returns Array of unified categories sorted: categories with templates first
 */
function buildUnifiedCategories(dynamicTemplates: Template[]): UnifiedAICategory[] {
  const categoryMap = new Map<string, AITemplate[]>()

  // 1. Flatten hardcoded AI_TEMPLATE_CATEGORIES into the map by template.category
  for (const group of AI_TEMPLATE_CATEGORIES) {
    for (const template of group.templates) {
      const existing = categoryMap.get(template.category) ?? []
      existing.push(template)
      categoryMap.set(template.category, existing)
    }
  }

  // 2. Add dynamic DB templates into the same map
  for (const t of dynamicTemplates) {
    const existing = categoryMap.get(t.category) ?? []
    existing.push({
      id: t.id,
      name: t.name,
      content: t.content,
      category: t.category,
      tags: t.tags,
    })
    categoryMap.set(t.category, existing)
  }

  // 3. Convert to unified category objects
  return Array.from(categoryMap.entries()).map(([categoryName, templates]) => {
    const colors = getCategoryColor(categoryName)
    return {
      id: `ai-cat-${categoryName.toLowerCase().replace(/\s+/g, "-")}`,
      name: categoryName,
      icon: React.createElement(IconSparkles, { className: "size-4" }),
      color: `${colors.badgeBg} ${colors.badgeText}`,
      borderColor: colors.border,
      templates,
    }
  })
}

/**
 * Unified AI template section with category-grouped cards.
 * Merges hardcoded templates with dynamically generated ones per category.
 *
 * @param props - Component props
 * @returns Section with category pills and merged AI template cards
 */
export function AITemplatesSection({
  onUseAITemplate,
  onSaveAITemplate,
  dynamicTemplates = [],
}: AITemplatesSectionProps) {
  const [activeCategory, setActiveCategory] = React.useState<string>("all")

  /** Unified categories: hardcoded + dynamic, grouped by actual category name */
  const allCategories = React.useMemo(
    () => buildUnifiedCategories(dynamicTemplates),
    [dynamicTemplates]
  )

  const filteredCategories = React.useMemo(() => {
    if (activeCategory === "all") return allCategories
    return allCategories.filter((c) => c.id === activeCategory)
  }, [activeCategory, allCategories])

  const allTabs = React.useMemo(
    () => [
      { id: "all", label: "All" },
      ...allCategories.map((c) => ({
        id: c.id,
        label: c.name,
        icon: c.icon,
        color: c.color,
      })),
    ],
    [allCategories]
  )

  return (
    <div className="flex flex-col gap-5">
      {/* Section header */}
      <div className="flex items-center gap-3">
        <div className="rounded-lg bg-gradient-to-br from-violet-500/15 to-purple-500/15 p-2.5">
          <IconSparkles className="size-5 text-violet-600 dark:text-violet-400" />
        </div>
        <div>
          <h2 className="text-base font-semibold">AI Templates</h2>
          <p className="text-muted-foreground text-sm">
            Pre-made templates to jumpstart your content
          </p>
        </div>
      </div>

      {/* Category filter pills */}
      <div className="flex flex-wrap gap-1.5">
        {allTabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveCategory(tab.id)}
            className={cn(
              "inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-medium transition-colors",
              activeCategory === tab.id
                ? "border-primary/30 bg-primary/10 text-primary"
                : "border-border bg-background text-muted-foreground hover:text-foreground hover:border-border/80"
            )}
          >
            {"icon" in tab && tab.icon && (
              <span className={cn("rounded p-0.5", "color" in tab ? tab.color : "")}>
                {tab.icon}
              </span>
            )}
            {tab.label}
          </button>
        ))}
      </div>

      {/* Template grid by unified category */}
      <div className="space-y-8">
        {filteredCategories.map((category) => (
          <div key={category.id}>
            <div className="flex items-center gap-2 mb-3">
              <span className={cn("rounded-lg p-1.5", category.color)}>
                {category.icon}
              </span>
              <h3 className="text-sm font-semibold">{category.name}</h3>
              <Badge variant="secondary" className="text-xs">
                {category.templates.length}
              </Badge>
            </div>
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {category.templates.map((template) => (
                <AITemplateCard
                  key={template.id}
                  template={template}
                  borderColor={category.borderColor}
                  onUse={onUseAITemplate}
                  onSave={onSaveAITemplate}
                />
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
