/**
 * Creative Template
 * Bold colorful style with vibrant gradients and dynamic typography
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * Creative template slides with bold, colorful styling
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Title Slide
  {
    id: 'creative-slide-1',
    backgroundColor: '#7c3aed',
    elements: [
      {
        id: 'creative-1-shape',
        type: 'shape',
        x: 600,
        y: -200,
        width: 800,
        height: 800,
        rotation: 45,
        shapeType: 'rect',
        fill: '#8b5cf6',
        cornerRadius: 40,
      },
      {
        id: 'creative-1-emoji',
        type: 'text',
        x: 80,
        y: 200,
        width: 200,
        height: 150,
        rotation: 0,
        text: '\u{1F680}',
        fontSize: 120,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'creative-1-title',
        type: 'text',
        x: 80,
        y: 400,
        width: 700,
        height: 150,
        rotation: 0,
        text: 'Stop Doing This!',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'creative-1-subtitle',
        type: 'text',
        x: 80,
        y: 560,
        width: 700,
        height: 80,
        rotation: 0,
        text: '(If You Want to Succeed)',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e9d5ff',
        align: 'left',
      },
      {
        id: 'creative-1-swipe',
        type: 'text',
        x: 80,
        y: 900,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'Swipe to learn more \u2192',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#c4b5fd',
        align: 'center',
      },
    ],
  },
  // Slide 2: Mistake 1
  {
    id: 'creative-slide-2',
    backgroundColor: '#ec4899',
    elements: [
      {
        id: 'creative-2-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 200,
        rotation: 0,
        text: '#1',
        fontSize: 120,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'creative-2-title',
        type: 'text',
        x: 80,
        y: 320,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'Waiting for the\n"Perfect" Moment',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'creative-2-content',
        type: 'text',
        x: 80,
        y: 520,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'The perfect moment doesn\'t exist. Start now, iterate later. Progress beats perfection every single time.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#fce7f3',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'creative-2-shape',
        type: 'shape',
        x: 800,
        y: 700,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#f472b6',
      },
    ],
  },
  // Slide 3: Mistake 2
  {
    id: 'creative-slide-3',
    backgroundColor: '#f59e0b',
    elements: [
      {
        id: 'creative-3-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 200,
        rotation: 0,
        text: '#2',
        fontSize: 120,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'creative-3-title',
        type: 'text',
        x: 80,
        y: 320,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'Comparing Your\nChapter 1 to Others',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'creative-3-content',
        type: 'text',
        x: 80,
        y: 520,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'You\'re seeing their highlight reel, not their behind-the-scenes. Focus on your own journey.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#fef3c7',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'creative-3-shape',
        type: 'shape',
        x: -100,
        y: 700,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#fbbf24',
      },
    ],
  },
  // Slide 4: Mistake 3
  {
    id: 'creative-slide-4',
    backgroundColor: '#10b981',
    elements: [
      {
        id: 'creative-4-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 200,
        rotation: 0,
        text: '#3',
        fontSize: 120,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'creative-4-title',
        type: 'text',
        x: 80,
        y: 320,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'Not Asking\nFor Help',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'creative-4-content',
        type: 'text',
        x: 80,
        y: 520,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'The most successful people aren\'t afraid to ask questions. Vulnerability is a strength, not a weakness.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#d1fae5',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'creative-4-shape',
        type: 'shape',
        x: 800,
        y: 700,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#34d399',
      },
    ],
  },
  // Slide 5: CTA
  {
    id: 'creative-slide-5',
    backgroundColor: '#7c3aed',
    elements: [
      {
        id: 'creative-5-shape1',
        type: 'shape',
        x: -100,
        y: -100,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#8b5cf6',
      },
      {
        id: 'creative-5-shape2',
        type: 'shape',
        x: 780,
        y: 780,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#a78bfa',
      },
      {
        id: 'creative-5-emoji',
        type: 'text',
        x: 440,
        y: 200,
        width: 200,
        height: 150,
        rotation: 0,
        text: '\u{1F389}',
        fontSize: 120,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'creative-5-title',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Now Go Do It!',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'creative-5-cta',
        type: 'text',
        x: 80,
        y: 540,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Like this? Follow for more!',
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e9d5ff',
        align: 'center',
      },
    ],
  },
];

/**
 * Creative template configuration
 */
export const creativeTemplate: CanvasTemplate = {
  id: 'creative-1',
  name: 'Bold & Colorful',
  description: 'Eye-catching design with vibrant colors and dynamic shapes for maximum engagement',
  category: 'creative',
  brandColors: ['#7c3aed', '#ec4899', '#f59e0b', '#10b981', '#ffffff'],
  fonts: ['Inter'],
  defaultSlides,
};
