/**
 * Cream and Orange Bold Entrepreneurship Template
 * Modern cream background with orange accents and bold black typography
 * Features: Checklist style, circular content blocks, brushstroke page numbers
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * Cream and Orange Bold Entrepreneurship template slides
 * Based on the "Cream and Orange Bold Modern Professional Entrepreneurship" Canva design
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Cover/Title Slide
  {
    id: 'coe-slide-1',
    backgroundColor: '#faf8f5',
    elements: [
      // Top label - "ENTREPRENEURSHIP"
      {
        id: 'coe-1-label',
        type: 'text',
        x: 80,
        y: 60,
        width: 920,
        height: 30,
        rotation: 0,
        text: 'E N T R E P R E N E U R S H I P',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#f97316',
        align: 'center',
        letterSpacing: 4,
      },
      // Main title
      {
        id: 'coe-1-title',
        type: 'text',
        x: 80,
        y: 320,
        width: 920,
        height: 300,
        rotation: 0,
        text: "The Founder's\nDaily Checklist:\nHow I Stay\nFocused & Sane",
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#1c1917',
        align: 'center',
        lineHeight: 1.2,
      },
      // CTA button background (brushstroke style - approximated with rect)
      {
        id: 'coe-1-cta-bg',
        type: 'shape',
        x: 380,
        y: 680,
        width: 280,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#f97316',
        cornerRadius: 4,
      },
      // CTA text
      {
        id: 'coe-1-cta',
        type: 'text',
        x: 380,
        y: 685,
        width: 280,
        height: 40,
        rotation: 0,
        text: 'Check details',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: '500',
        fontStyle: 'italic',
        fill: '#ffffff',
        align: 'center',
      },
      // Arrow decoration
      {
        id: 'coe-1-arrow',
        type: 'text',
        x: 660,
        y: 670,
        width: 100,
        height: 60,
        rotation: 0,
        text: '↗',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#f97316',
        align: 'left',
      },
      // Author/Brand name
      {
        id: 'coe-1-author',
        type: 'text',
        x: 80,
        y: 920,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'Studio Shodwe',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#1c1917',
        align: 'center',
      },
    ],
  },
  // Slide 2: Why This Matters
  {
    id: 'coe-slide-2',
    backgroundColor: '#faf8f5',
    elements: [
      // Top label
      {
        id: 'coe-2-label',
        type: 'text',
        x: 80,
        y: 60,
        width: 920,
        height: 30,
        rotation: 0,
        text: 'E N T R E P R E N E U R S H I P',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#f97316',
        align: 'center',
        letterSpacing: 4,
      },
      // Main title
      {
        id: 'coe-2-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 150,
        rotation: 0,
        text: 'Why This\nMatters?',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#1c1917',
        align: 'center',
        lineHeight: 1.1,
      },
      // Description
      {
        id: 'coe-2-desc',
        type: 'text',
        x: 120,
        y: 480,
        width: 840,
        height: 200,
        rotation: 0,
        text: 'Foundership can feel like 27 tabs\nopen all the time.\nThis simple checklist keeps me\ngrounded, sharp, and moving\nforward — daily.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'center',
        lineHeight: 1.6,
      },
      // Page number background (brushstroke)
      {
        id: 'coe-2-page-bg',
        type: 'shape',
        x: 460,
        y: 920,
        width: 160,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#f97316',
        cornerRadius: 4,
      },
      // Page number
      {
        id: 'coe-2-page',
        type: 'text',
        x: 460,
        y: 925,
        width: 160,
        height: 40,
        rotation: 0,
        text: '2',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 3: Morning Kickstart (Checklist)
  {
    id: 'coe-slide-3',
    backgroundColor: '#faf8f5',
    elements: [
      // Top label
      {
        id: 'coe-3-label',
        type: 'text',
        x: 80,
        y: 60,
        width: 920,
        height: 30,
        rotation: 0,
        text: 'E N T R E P R E N E U R S H I P',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#f97316',
        align: 'center',
        letterSpacing: 4,
      },
      // Section title
      {
        id: 'coe-3-title',
        type: 'text',
        x: 80,
        y: 200,
        width: 600,
        height: 140,
        rotation: 0,
        text: 'Morning\nKickstart',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#1c1917',
        align: 'left',
        lineHeight: 1.1,
      },
      // Subtitle
      {
        id: 'coe-3-subtitle',
        type: 'text',
        x: 80,
        y: 400,
        width: 600,
        height: 40,
        rotation: 0,
        text: 'Before checking emails or socials:',
        fontSize: 22,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
      },
      // Checkbox 1 box
      {
        id: 'coe-3-check1-box',
        type: 'shape',
        x: 80,
        y: 470,
        width: 30,
        height: 30,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#1c1917',
        strokeWidth: 2,
        cornerRadius: 4,
      },
      // Checkbox 1 text
      {
        id: 'coe-3-check1',
        type: 'text',
        x: 130,
        y: 470,
        width: 700,
        height: 35,
        rotation: 0,
        text: 'Review top 3 priorities',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
      },
      // Checkbox 2 box
      {
        id: 'coe-3-check2-box',
        type: 'shape',
        x: 80,
        y: 530,
        width: 30,
        height: 30,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#1c1917',
        strokeWidth: 2,
        cornerRadius: 4,
      },
      // Checkbox 2 text
      {
        id: 'coe-3-check2',
        type: 'text',
        x: 130,
        y: 530,
        width: 700,
        height: 35,
        rotation: 0,
        text: '5-minute journal (what matters today?)',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
      },
      // Checkbox 3 box
      {
        id: 'coe-3-check3-box',
        type: 'shape',
        x: 80,
        y: 590,
        width: 30,
        height: 30,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#1c1917',
        strokeWidth: 2,
        cornerRadius: 4,
      },
      // Checkbox 3 text
      {
        id: 'coe-3-check3',
        type: 'text',
        x: 130,
        y: 590,
        width: 700,
        height: 35,
        rotation: 0,
        text: '15-min walk or stretch (no phone)',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
      },
      // Page number background
      {
        id: 'coe-3-page-bg',
        type: 'shape',
        x: 460,
        y: 920,
        width: 160,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#f97316',
        cornerRadius: 4,
      },
      // Page number
      {
        id: 'coe-3-page',
        type: 'text',
        x: 460,
        y: 925,
        width: 160,
        height: 40,
        rotation: 0,
        text: '3',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 4: Focus Blocks (Circle design)
  {
    id: 'coe-slide-4',
    backgroundColor: '#faf8f5',
    elements: [
      // Top label
      {
        id: 'coe-4-label',
        type: 'text',
        x: 80,
        y: 60,
        width: 920,
        height: 30,
        rotation: 0,
        text: 'E N T R E P R E N E U R S H I P',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#f97316',
        align: 'center',
        letterSpacing: 4,
      },
      // Main title
      {
        id: 'coe-4-title',
        type: 'text',
        x: 80,
        y: 180,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'Focus\nBlocks',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#1c1917',
        align: 'center',
        lineHeight: 1.1,
      },
      // Block 1 circle
      {
        id: 'coe-4-circle1',
        type: 'shape',
        x: 120,
        y: 400,
        width: 360,
        height: 360,
        rotation: 0,
        shapeType: 'circle',
        fill: 'transparent',
        stroke: '#1c1917',
        strokeWidth: 2,
      },
      // Block 1 title
      {
        id: 'coe-4-block1-title',
        type: 'text',
        x: 120,
        y: 480,
        width: 360,
        height: 50,
        rotation: 0,
        text: 'Block 1',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#1c1917',
        align: 'center',
      },
      // Block 1 description
      {
        id: 'coe-4-block1-desc',
        type: 'text',
        x: 140,
        y: 540,
        width: 320,
        height: 120,
        rotation: 0,
        text: '90 mins for creation\n(product, content,\nstrategy)',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'center',
        lineHeight: 1.4,
      },
      // Block 2 circle
      {
        id: 'coe-4-circle2',
        type: 'shape',
        x: 600,
        y: 400,
        width: 360,
        height: 360,
        rotation: 0,
        shapeType: 'circle',
        fill: 'transparent',
        stroke: '#1c1917',
        strokeWidth: 2,
      },
      // Block 2 title
      {
        id: 'coe-4-block2-title',
        type: 'text',
        x: 600,
        y: 480,
        width: 360,
        height: 50,
        rotation: 0,
        text: 'Block 2',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#1c1917',
        align: 'center',
      },
      // Block 2 description
      {
        id: 'coe-4-block2-desc',
        type: 'text',
        x: 620,
        y: 540,
        width: 320,
        height: 120,
        rotation: 0,
        text: '90 mins for execution\n(team, tasks, follow-\nups)',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'center',
        lineHeight: 1.4,
      },
      // Page number background
      {
        id: 'coe-4-page-bg',
        type: 'shape',
        x: 460,
        y: 920,
        width: 160,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#f97316',
        cornerRadius: 4,
      },
      // Page number
      {
        id: 'coe-4-page',
        type: 'text',
        x: 460,
        y: 925,
        width: 160,
        height: 40,
        rotation: 0,
        text: '4',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 5: CTA Slide
  {
    id: 'coe-slide-5',
    backgroundColor: '#faf8f5',
    elements: [
      // Top label
      {
        id: 'coe-5-label',
        type: 'text',
        x: 80,
        y: 60,
        width: 920,
        height: 30,
        rotation: 0,
        text: 'E N T R E P R E N E U R S H I P',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#f97316',
        align: 'center',
        letterSpacing: 4,
      },
      // Main CTA title
      {
        id: 'coe-5-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 250,
        rotation: 0,
        text: 'Want a copy of\nthis as a printable\nchecklist?',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '800',
        fill: '#1c1917',
        align: 'center',
        lineHeight: 1.2,
      },
      // Subtitle
      {
        id: 'coe-5-subtitle',
        type: 'text',
        x: 120,
        y: 580,
        width: 840,
        height: 100,
        rotation: 0,
        text: "Drop a comment and I'll send it your way.\nOr save this for your next reset day.",
        fontSize: 26,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'center',
        lineHeight: 1.6,
      },
      // Author/Brand name
      {
        id: 'coe-5-author',
        type: 'text',
        x: 80,
        y: 900,
        width: 920,
        height: 50,
        rotation: 0,
        text: 'Studio Shodwe',
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: '700',
        fill: '#f97316',
        align: 'center',
      },
    ],
  },
];

/**
 * Cream and Orange Bold Entrepreneurship template configuration
 * Modern cream design with orange accents, perfect for entrepreneurship and business content
 */
export const creamOrangeEntrepreneurshipTemplate: CanvasTemplate = {
  id: 'cream-orange-entrepreneurship-1',
  name: 'Cream & Orange Entrepreneurship',
  description: 'Bold modern design with cream background and orange accents, perfect for founders, entrepreneurs, and business tips',
  category: 'bold',
  brandColors: ['#faf8f5', '#f97316', '#1c1917', '#57534e', '#ffffff'],
  fonts: ['Inter'],
  defaultSlides,
};
