/**
 * Default Carousel Templates
 * Six professional templates covering common LinkedIn carousel styles
 * @module lib/canvas-templates/default-templates
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

// ============================================================
// 1. MINIMALIST TEMPLATE
// Clean white background, simple black text, subtle accent lines
// ============================================================

/**
 * Minimalist template slides with clean, airy design
 */
const minimalistSlides: CanvasSlide[] = [
  {
    id: 'min-slide-1',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'min-1-accent-top',
        type: 'shape',
        x: 80,
        y: 80,
        width: 60,
        height: 3,
        rotation: 0,
        shapeType: 'rect',
        fill: '#000000',
        cornerRadius: 2,
      },
      {
        id: 'min-1-title',
        type: 'text',
        x: 80,
        y: 360,
        width: 920,
        height: 140,
        rotation: 0,
        text: 'Simple Ideas.\nBig Impact.',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#111111',
        align: 'left',
        lineHeight: 1.15,
      },
      {
        id: 'min-1-subtitle',
        type: 'text',
        x: 80,
        y: 540,
        width: 600,
        height: 50,
        rotation: 0,
        text: 'A guide to clarity in content',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#888888',
        align: 'left',
      },
      {
        id: 'min-1-accent-bottom',
        type: 'shape',
        x: 80,
        y: 960,
        width: 60,
        height: 3,
        rotation: 0,
        shapeType: 'rect',
        fill: '#000000',
        cornerRadius: 2,
      },
    ],
  },
  {
    id: 'min-slide-2',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'min-2-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 100,
        height: 40,
        rotation: 0,
        text: '01',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#aaaaaa',
        align: 'left',
      },
      {
        id: 'min-2-line',
        type: 'shape',
        x: 80,
        y: 140,
        width: 40,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#111111',
        cornerRadius: 1,
      },
      {
        id: 'min-2-heading',
        type: 'text',
        x: 80,
        y: 200,
        width: 700,
        height: 120,
        rotation: 0,
        text: 'Start with why',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#111111',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'min-2-body',
        type: 'text',
        x: 80,
        y: 380,
        width: 700,
        height: 200,
        rotation: 0,
        text: 'Every great piece of content starts with a clear purpose. Know your message before you write a single word.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#666666',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'min-slide-3',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'min-3-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 100,
        height: 40,
        rotation: 0,
        text: '02',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#aaaaaa',
        align: 'left',
      },
      {
        id: 'min-3-line',
        type: 'shape',
        x: 80,
        y: 140,
        width: 40,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#111111',
        cornerRadius: 1,
      },
      {
        id: 'min-3-heading',
        type: 'text',
        x: 80,
        y: 200,
        width: 700,
        height: 120,
        rotation: 0,
        text: 'Cut the clutter',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#111111',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'min-3-body',
        type: 'text',
        x: 80,
        y: 380,
        width: 700,
        height: 200,
        rotation: 0,
        text: 'Remove anything that does not serve your reader. Brevity is not about saying less, it is about saying only what matters.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#666666',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'min-slide-4',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'min-4-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 100,
        height: 40,
        rotation: 0,
        text: '03',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#aaaaaa',
        align: 'left',
      },
      {
        id: 'min-4-line',
        type: 'shape',
        x: 80,
        y: 140,
        width: 40,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#111111',
        cornerRadius: 1,
      },
      {
        id: 'min-4-heading',
        type: 'text',
        x: 80,
        y: 200,
        width: 700,
        height: 120,
        rotation: 0,
        text: 'Let it breathe',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#111111',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'min-4-body',
        type: 'text',
        x: 80,
        y: 380,
        width: 700,
        height: 200,
        rotation: 0,
        text: 'White space is your friend. Give your ideas room to land. Readers need visual breathing room.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#666666',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'min-slide-5',
    backgroundColor: '#111111',
    elements: [
      {
        id: 'min-5-accent',
        type: 'shape',
        x: 80,
        y: 80,
        width: 60,
        height: 3,
        rotation: 0,
        shapeType: 'rect',
        fill: '#ffffff',
        cornerRadius: 2,
      },
      {
        id: 'min-5-cta',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Less noise.\nMore signal.',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'min-5-follow',
        type: 'text',
        x: 80,
        y: 560,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'Follow for more',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#888888',
        align: 'left',
      },
    ],
  },
];

/**
 * Minimalist template configuration
 */
export const minimalistTemplate: CanvasTemplate = {
  id: 'default-minimalist',
  name: 'Minimalist',
  description: 'Clean white backgrounds with simple black text and subtle accent lines. Perfect for thought leadership.',
  category: 'minimal',
  brandColors: ['#ffffff', '#111111', '#666666', '#aaaaaa', '#888888'],
  fonts: ['Inter'],
  defaultSlides: minimalistSlides,
  isFavorite: false,
};

// ============================================================
// 2. BOLD IMPACT TEMPLATE
// Dark background, large white text, accent color highlights
// ============================================================

/**
 * Bold Impact template slides with dark, high-contrast design
 */
const boldImpactSlides: CanvasSlide[] = [
  {
    id: 'bold-slide-1',
    backgroundColor: '#0a0a0a',
    elements: [
      {
        id: 'bold-1-accent-bar',
        type: 'shape',
        x: 0,
        y: 0,
        width: 1080,
        height: 8,
        rotation: 0,
        shapeType: 'rect',
        fill: '#ff6b35',
      },
      {
        id: 'bold-1-title',
        type: 'text',
        x: 80,
        y: 300,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'STOP\nSCROLLING.',
        fontSize: 96,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.05,
      },
      {
        id: 'bold-1-subtitle',
        type: 'text',
        x: 80,
        y: 540,
        width: 700,
        height: 60,
        rotation: 0,
        text: 'This will change how you think.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ff6b35',
        align: 'left',
      },
      {
        id: 'bold-1-swipe',
        type: 'text',
        x: 80,
        y: 940,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'SWIPE >>',
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#555555',
        align: 'center',
      },
    ],
  },
  {
    id: 'bold-slide-2',
    backgroundColor: '#0a0a0a',
    elements: [
      {
        id: 'bold-2-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 120,
        rotation: 0,
        text: '01',
        fontSize: 100,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#ff6b35',
        align: 'left',
      },
      {
        id: 'bold-2-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'THE HARD TRUTH',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'bold-2-body',
        type: 'text',
        x: 80,
        y: 420,
        width: 920,
        height: 250,
        rotation: 0,
        text: 'Most people spend 80% of their time on things that produce only 20% of the results. Flip the ratio.',
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#cccccc',
        align: 'left',
        lineHeight: 1.5,
      },
    ],
  },
  {
    id: 'bold-slide-3',
    backgroundColor: '#0a0a0a',
    elements: [
      {
        id: 'bold-3-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 120,
        rotation: 0,
        text: '02',
        fontSize: 100,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#ff6b35',
        align: 'left',
      },
      {
        id: 'bold-3-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'THE SHIFT',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'bold-3-body',
        type: 'text',
        x: 80,
        y: 420,
        width: 920,
        height: 250,
        rotation: 0,
        text: 'Success is not about working harder. It is about working on the right things at the right time.',
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#cccccc',
        align: 'left',
        lineHeight: 1.5,
      },
    ],
  },
  {
    id: 'bold-slide-4',
    backgroundColor: '#0a0a0a',
    elements: [
      {
        id: 'bold-4-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 120,
        rotation: 0,
        text: '03',
        fontSize: 100,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#ff6b35',
        align: 'left',
      },
      {
        id: 'bold-4-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'THE ACTION',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'bold-4-body',
        type: 'text',
        x: 80,
        y: 420,
        width: 920,
        height: 250,
        rotation: 0,
        text: 'Audit your calendar. Eliminate distractions ruthlessly. Protect your peak hours for deep work.',
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#cccccc',
        align: 'left',
        lineHeight: 1.5,
      },
    ],
  },
  {
    id: 'bold-slide-5',
    backgroundColor: '#ff6b35',
    elements: [
      {
        id: 'bold-5-title',
        type: 'text',
        x: 80,
        y: 360,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'NOW GO\nDO IT.',
        fontSize: 80,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#0a0a0a',
        align: 'left',
        lineHeight: 1.05,
      },
      {
        id: 'bold-5-cta',
        type: 'text',
        x: 80,
        y: 540,
        width: 920,
        height: 50,
        rotation: 0,
        text: 'Like + Follow for more',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#0a0a0a',
        align: 'left',
      },
    ],
  },
];

/**
 * Bold Impact template configuration
 */
export const boldImpactTemplate: CanvasTemplate = {
  id: 'default-bold-impact',
  name: 'Bold Impact',
  description: 'Dark backgrounds with large white text and accent color highlights. Maximum visual impact.',
  category: 'bold',
  brandColors: ['#0a0a0a', '#ffffff', '#ff6b35', '#cccccc', '#555555'],
  fonts: ['Inter'],
  defaultSlides: boldImpactSlides,
  isFavorite: false,
};

// ============================================================
// 3. CORPORATE PROFESSIONAL TEMPLATE
// LinkedIn blue theme, structured layouts, logo placeholder
// ============================================================

/**
 * Corporate Professional template slides with LinkedIn blue styling
 */
const corporateSlides: CanvasSlide[] = [
  {
    id: 'corp-slide-1',
    backgroundColor: '#0077b5',
    elements: [
      {
        id: 'corp-1-logo-placeholder',
        type: 'shape',
        x: 80,
        y: 80,
        width: 80,
        height: 80,
        rotation: 0,
        shapeType: 'rect',
        fill: '#ffffff',
        cornerRadius: 12,
      },
      {
        id: 'corp-1-logo-text',
        type: 'text',
        x: 80,
        y: 92,
        width: 80,
        height: 60,
        rotation: 0,
        text: 'LOGO',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#0077b5',
        align: 'center',
      },
      {
        id: 'corp-1-title',
        type: 'text',
        x: 80,
        y: 340,
        width: 920,
        height: 140,
        rotation: 0,
        text: 'Industry Report\n2025',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.15,
      },
      {
        id: 'corp-1-divider',
        type: 'shape',
        x: 80,
        y: 520,
        width: 120,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#ffffff',
        cornerRadius: 2,
      },
      {
        id: 'corp-1-subtitle',
        type: 'text',
        x: 80,
        y: 560,
        width: 700,
        height: 60,
        rotation: 0,
        text: 'Key Trends and Insights for Leaders',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#b3d9f0',
        align: 'left',
      },
      {
        id: 'corp-1-author',
        type: 'text',
        x: 80,
        y: 920,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'Your Company Name',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#ffffff',
        align: 'left',
      },
    ],
  },
  {
    id: 'corp-slide-2',
    backgroundColor: '#f8fafc',
    elements: [
      {
        id: 'corp-2-sidebar',
        type: 'shape',
        x: 0,
        y: 0,
        width: 8,
        height: 1080,
        rotation: 0,
        shapeType: 'rect',
        fill: '#0077b5',
      },
      {
        id: 'corp-2-label',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TREND 01',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#0077b5',
        align: 'left',
        letterSpacing: 2,
      },
      {
        id: 'corp-2-title',
        type: 'text',
        x: 80,
        y: 150,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Digital Transformation\nAccelerates',
        fontSize: 44,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e293b',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'corp-2-body',
        type: 'text',
        x: 80,
        y: 320,
        width: 920,
        height: 250,
        rotation: 0,
        text: 'Organizations that invest in digital infrastructure see 2.5x faster growth. The shift is no longer optional but a competitive necessity.',
        fontSize: 26,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'corp-2-stat-bg',
        type: 'shape',
        x: 80,
        y: 640,
        width: 920,
        height: 120,
        rotation: 0,
        shapeType: 'rect',
        fill: '#e0f2fe',
        cornerRadius: 12,
      },
      {
        id: 'corp-2-stat',
        type: 'text',
        x: 120,
        y: 665,
        width: 840,
        height: 70,
        rotation: 0,
        text: '73% of executives report this as their top priority',
        fontSize: 22,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#0077b5',
        align: 'left',
      },
    ],
  },
  {
    id: 'corp-slide-3',
    backgroundColor: '#f8fafc',
    elements: [
      {
        id: 'corp-3-sidebar',
        type: 'shape',
        x: 0,
        y: 0,
        width: 8,
        height: 1080,
        rotation: 0,
        shapeType: 'rect',
        fill: '#0077b5',
      },
      {
        id: 'corp-3-label',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TREND 02',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#0077b5',
        align: 'left',
        letterSpacing: 2,
      },
      {
        id: 'corp-3-title',
        type: 'text',
        x: 80,
        y: 150,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'AI-Driven Decision\nMaking',
        fontSize: 44,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e293b',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'corp-3-body',
        type: 'text',
        x: 80,
        y: 320,
        width: 920,
        height: 250,
        rotation: 0,
        text: 'Companies leveraging AI for strategic decisions outperform peers by 40%. Integration across workflows is the key differentiator.',
        fontSize: 26,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'corp-3-stat-bg',
        type: 'shape',
        x: 80,
        y: 640,
        width: 920,
        height: 120,
        rotation: 0,
        shapeType: 'rect',
        fill: '#e0f2fe',
        cornerRadius: 12,
      },
      {
        id: 'corp-3-stat',
        type: 'text',
        x: 120,
        y: 665,
        width: 840,
        height: 70,
        rotation: 0,
        text: '58% of teams now use AI tools daily in their workflow',
        fontSize: 22,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#0077b5',
        align: 'left',
      },
    ],
  },
  {
    id: 'corp-slide-4',
    backgroundColor: '#f8fafc',
    elements: [
      {
        id: 'corp-4-sidebar',
        type: 'shape',
        x: 0,
        y: 0,
        width: 8,
        height: 1080,
        rotation: 0,
        shapeType: 'rect',
        fill: '#0077b5',
      },
      {
        id: 'corp-4-label',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TREND 03',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#0077b5',
        align: 'left',
        letterSpacing: 2,
      },
      {
        id: 'corp-4-title',
        type: 'text',
        x: 80,
        y: 150,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Remote-First\nCulture Wins',
        fontSize: 44,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e293b',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'corp-4-body',
        type: 'text',
        x: 80,
        y: 320,
        width: 920,
        height: 250,
        rotation: 0,
        text: 'Distributed teams with strong async communication report higher retention and productivity. Culture beats location.',
        fontSize: 26,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'corp-4-stat-bg',
        type: 'shape',
        x: 80,
        y: 640,
        width: 920,
        height: 120,
        rotation: 0,
        shapeType: 'rect',
        fill: '#e0f2fe',
        cornerRadius: 12,
      },
      {
        id: 'corp-4-stat',
        type: 'text',
        x: 120,
        y: 665,
        width: 840,
        height: 70,
        rotation: 0,
        text: '65% of workers prefer flexible arrangements over salary raises',
        fontSize: 22,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#0077b5',
        align: 'left',
      },
    ],
  },
  {
    id: 'corp-slide-5',
    backgroundColor: '#0077b5',
    elements: [
      {
        id: 'corp-5-logo-placeholder',
        type: 'shape',
        x: 480,
        y: 200,
        width: 120,
        height: 120,
        rotation: 0,
        shapeType: 'rect',
        fill: '#ffffff',
        cornerRadius: 16,
      },
      {
        id: 'corp-5-logo-text',
        type: 'text',
        x: 480,
        y: 220,
        width: 120,
        height: 80,
        rotation: 0,
        text: 'LOGO',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#0077b5',
        align: 'center',
      },
      {
        id: 'corp-5-title',
        type: 'text',
        x: 80,
        y: 420,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'Want the full report?',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'corp-5-cta',
        type: 'text',
        x: 80,
        y: 530,
        width: 920,
        height: 50,
        rotation: 0,
        text: 'Follow us + Comment "REPORT" below',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#b3d9f0',
        align: 'center',
      },
    ],
  },
];

/**
 * Corporate Professional template configuration
 */
export const corporateProfessionalTemplate: CanvasTemplate = {
  id: 'default-corporate',
  name: 'Corporate Professional',
  description: 'LinkedIn blue theme with structured layouts and logo placeholders. Ideal for company content.',
  category: 'professional',
  brandColors: ['#0077b5', '#f8fafc', '#1e293b', '#b3d9f0', '#e0f2fe'],
  fonts: ['Inter'],
  defaultSlides: corporateSlides,
  isFavorite: false,
};

// ============================================================
// 4. CREATIVE GRADIENT TEMPLATE
// Gradient backgrounds, modern typography, decorative shapes
// ============================================================

/**
 * Creative Gradient template slides with vibrant, modern design
 */
const creativeGradientSlides: CanvasSlide[] = [
  {
    id: 'grad-slide-1',
    backgroundColor: '#1a1a2e',
    elements: [
      {
        id: 'grad-1-circle1',
        type: 'shape',
        x: -150,
        y: -150,
        width: 500,
        height: 500,
        rotation: 0,
        shapeType: 'circle',
        fill: '#e94560',
      },
      {
        id: 'grad-1-circle2',
        type: 'shape',
        x: 730,
        y: 680,
        width: 500,
        height: 500,
        rotation: 0,
        shapeType: 'circle',
        fill: '#533483',
      },
      {
        id: 'grad-1-title',
        type: 'text',
        x: 80,
        y: 380,
        width: 920,
        height: 150,
        rotation: 0,
        text: 'Design Your\nFuture',
        fontSize: 80,
        fontFamily: 'Montserrat',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
        lineHeight: 1.1,
      },
      {
        id: 'grad-1-subtitle',
        type: 'text',
        x: 80,
        y: 570,
        width: 920,
        height: 50,
        rotation: 0,
        text: '5 creative strategies for growth',
        fontSize: 24,
        fontFamily: 'Montserrat',
        fontWeight: 'normal',
        fill: '#e8d5f5',
        align: 'center',
      },
    ],
  },
  {
    id: 'grad-slide-2',
    backgroundColor: '#16213e',
    elements: [
      {
        id: 'grad-2-circle',
        type: 'shape',
        x: 780,
        y: -100,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#e94560',
      },
      {
        id: 'grad-2-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 130,
        rotation: 0,
        text: '01',
        fontSize: 100,
        fontFamily: 'Montserrat',
        fontWeight: '900',
        fill: '#e94560',
        align: 'left',
      },
      {
        id: 'grad-2-title',
        type: 'text',
        x: 80,
        y: 260,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'Think Differently',
        fontSize: 48,
        fontFamily: 'Montserrat',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'grad-2-body',
        type: 'text',
        x: 80,
        y: 380,
        width: 800,
        height: 200,
        rotation: 0,
        text: 'Innovation comes from challenging assumptions. Question everything you think you know about your industry.',
        fontSize: 26,
        fontFamily: 'Montserrat',
        fontWeight: 'normal',
        fill: '#c8b6e2',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'grad-slide-3',
    backgroundColor: '#1a1a2e',
    elements: [
      {
        id: 'grad-3-circle',
        type: 'shape',
        x: -100,
        y: 680,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#533483',
      },
      {
        id: 'grad-3-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 130,
        rotation: 0,
        text: '02',
        fontSize: 100,
        fontFamily: 'Montserrat',
        fontWeight: '900',
        fill: '#e94560',
        align: 'left',
      },
      {
        id: 'grad-3-title',
        type: 'text',
        x: 80,
        y: 260,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'Build in Public',
        fontSize: 48,
        fontFamily: 'Montserrat',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'grad-3-body',
        type: 'text',
        x: 80,
        y: 380,
        width: 800,
        height: 200,
        rotation: 0,
        text: 'Share your process, not just the results. Vulnerability and transparency build deeper connections.',
        fontSize: 26,
        fontFamily: 'Montserrat',
        fontWeight: 'normal',
        fill: '#c8b6e2',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'grad-slide-4',
    backgroundColor: '#16213e',
    elements: [
      {
        id: 'grad-4-rect',
        type: 'shape',
        x: 700,
        y: 600,
        width: 500,
        height: 500,
        rotation: 30,
        shapeType: 'rect',
        fill: '#e94560',
        cornerRadius: 40,
      },
      {
        id: 'grad-4-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 130,
        rotation: 0,
        text: '03',
        fontSize: 100,
        fontFamily: 'Montserrat',
        fontWeight: '900',
        fill: '#e94560',
        align: 'left',
      },
      {
        id: 'grad-4-title',
        type: 'text',
        x: 80,
        y: 260,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'Embrace the Chaos',
        fontSize: 48,
        fontFamily: 'Montserrat',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'grad-4-body',
        type: 'text',
        x: 80,
        y: 380,
        width: 800,
        height: 200,
        rotation: 0,
        text: 'Growth rarely follows a straight line. Learn to thrive in ambiguity and turn uncertainty into opportunity.',
        fontSize: 26,
        fontFamily: 'Montserrat',
        fontWeight: 'normal',
        fill: '#c8b6e2',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  {
    id: 'grad-slide-5',
    backgroundColor: '#e94560',
    elements: [
      {
        id: 'grad-5-circle',
        type: 'shape',
        x: 340,
        y: 150,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#533483',
      },
      {
        id: 'grad-5-title',
        type: 'text',
        x: 80,
        y: 380,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Ready to Create?',
        fontSize: 64,
        fontFamily: 'Montserrat',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'grad-5-cta',
        type: 'text',
        x: 80,
        y: 510,
        width: 920,
        height: 50,
        rotation: 0,
        text: 'Follow + Save for later',
        fontSize: 28,
        fontFamily: 'Montserrat',
        fontWeight: 'normal',
        fill: '#1a1a2e',
        align: 'center',
      },
    ],
  },
];

/**
 * Creative Gradient template configuration
 */
export const creativeGradientTemplate: CanvasTemplate = {
  id: 'default-creative-gradient',
  name: 'Creative Gradient',
  description: 'Vibrant gradient backgrounds with modern typography and decorative shapes. Stand out in the feed.',
  category: 'creative',
  brandColors: ['#1a1a2e', '#e94560', '#533483', '#16213e', '#c8b6e2'],
  fonts: ['Montserrat'],
  defaultSlides: creativeGradientSlides,
  isFavorite: false,
};

// ============================================================
// 5. DATA STORYTELLING TEMPLATE
// Charts/data-friendly layout, numbered slides, clean grid
// ============================================================

/**
 * Data Storytelling template slides with data-focused design
 */
const dataStorytellingSlides: CanvasSlide[] = [
  {
    id: 'data-slide-1',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'data-1-tag',
        type: 'shape',
        x: 80,
        y: 80,
        width: 140,
        height: 36,
        rotation: 0,
        shapeType: 'rect',
        fill: '#22d3ee',
        cornerRadius: 18,
      },
      {
        id: 'data-1-tag-text',
        type: 'text',
        x: 80,
        y: 84,
        width: 140,
        height: 30,
        rotation: 0,
        text: 'DATA DEEP DIVE',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#0f172a',
        align: 'center',
        letterSpacing: 1,
      },
      {
        id: 'data-1-title',
        type: 'text',
        x: 80,
        y: 300,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'The Numbers\nDon\'t Lie',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.15,
      },
      {
        id: 'data-1-subtitle',
        type: 'text',
        x: 80,
        y: 540,
        width: 700,
        height: 50,
        rotation: 0,
        text: '5 data points every leader should know',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#94a3b8',
        align: 'left',
      },
      {
        id: 'data-1-line',
        type: 'shape',
        x: 80,
        y: 900,
        width: 920,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1e293b',
        cornerRadius: 1,
      },
      {
        id: 'data-1-footer',
        type: 'text',
        x: 80,
        y: 930,
        width: 920,
        height: 30,
        rotation: 0,
        text: '1 / 6',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'right',
      },
    ],
  },
  {
    id: 'data-slide-2',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'data-2-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 120,
        height: 60,
        rotation: 0,
        text: '#1',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#22d3ee',
        align: 'left',
      },
      {
        id: 'data-2-stat',
        type: 'text',
        x: 80,
        y: 200,
        width: 600,
        height: 130,
        rotation: 0,
        text: '87%',
        fontSize: 120,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#22d3ee',
        align: 'left',
      },
      {
        id: 'data-2-title',
        type: 'text',
        x: 80,
        y: 370,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'of buyers research online first',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'data-2-body',
        type: 'text',
        x: 80,
        y: 490,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Your online presence is often the first impression. Make sure it tells the right story about your brand.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#94a3b8',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'data-2-line',
        type: 'shape',
        x: 80,
        y: 900,
        width: 920,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1e293b',
        cornerRadius: 1,
      },
      {
        id: 'data-2-footer',
        type: 'text',
        x: 80,
        y: 930,
        width: 920,
        height: 30,
        rotation: 0,
        text: '2 / 6',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'right',
      },
    ],
  },
  {
    id: 'data-slide-3',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'data-3-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 120,
        height: 60,
        rotation: 0,
        text: '#2',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#22d3ee',
        align: 'left',
      },
      {
        id: 'data-3-stat',
        type: 'text',
        x: 80,
        y: 200,
        width: 600,
        height: 130,
        rotation: 0,
        text: '3.2x',
        fontSize: 120,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#22d3ee',
        align: 'left',
      },
      {
        id: 'data-3-title',
        type: 'text',
        x: 80,
        y: 370,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'more engagement with carousels',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'data-3-body',
        type: 'text',
        x: 80,
        y: 490,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Carousel posts consistently outperform single-image posts. The swipe mechanic keeps people engaged longer.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#94a3b8',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'data-3-line',
        type: 'shape',
        x: 80,
        y: 900,
        width: 920,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1e293b',
        cornerRadius: 1,
      },
      {
        id: 'data-3-footer',
        type: 'text',
        x: 80,
        y: 930,
        width: 920,
        height: 30,
        rotation: 0,
        text: '3 / 6',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'right',
      },
    ],
  },
  {
    id: 'data-slide-4',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'data-4-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 120,
        height: 60,
        rotation: 0,
        text: '#3',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#22d3ee',
        align: 'left',
      },
      {
        id: 'data-4-stat',
        type: 'text',
        x: 80,
        y: 200,
        width: 600,
        height: 130,
        rotation: 0,
        text: '47%',
        fontSize: 120,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#22d3ee',
        align: 'left',
      },
      {
        id: 'data-4-title',
        type: 'text',
        x: 80,
        y: 370,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'higher ROI from content marketing',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'data-4-body',
        type: 'text',
        x: 80,
        y: 490,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Consistent, high-quality content builds trust over time. The compound effect of regular publishing is real.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#94a3b8',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'data-4-line',
        type: 'shape',
        x: 80,
        y: 900,
        width: 920,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1e293b',
        cornerRadius: 1,
      },
      {
        id: 'data-4-footer',
        type: 'text',
        x: 80,
        y: 930,
        width: 920,
        height: 30,
        rotation: 0,
        text: '4 / 6',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'right',
      },
    ],
  },
  {
    id: 'data-slide-5',
    backgroundColor: '#22d3ee',
    elements: [
      {
        id: 'data-5-title',
        type: 'text',
        x: 80,
        y: 350,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Data wins arguments.',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#0f172a',
        align: 'center',
      },
      {
        id: 'data-5-subtitle',
        type: 'text',
        x: 80,
        y: 480,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Save this carousel for your next presentation.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#0f172a',
        align: 'center',
      },
      {
        id: 'data-5-cta',
        type: 'text',
        x: 80,
        y: 600,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'Follow @yourhandle for more data insights',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#164e63',
        align: 'center',
      },
    ],
  },
];

/**
 * Data Storytelling template configuration
 */
export const dataStorytellingTemplate: CanvasTemplate = {
  id: 'default-data-storytelling',
  name: 'Data Storytelling',
  description: 'Data-friendly layouts with large statistics, numbered slides, and clean grid. Perfect for insights.',
  category: 'professional',
  brandColors: ['#0f172a', '#22d3ee', '#ffffff', '#94a3b8', '#1e293b'],
  fonts: ['Inter'],
  defaultSlides: dataStorytellingSlides,
  isFavorite: false,
};

// ============================================================
// 6. STORY ARC TEMPLATE
// Hook slide, 4 content slides, CTA slide, narrative structure
// ============================================================

/**
 * Story Arc template slides with narrative progression structure
 */
const storyArcSlides: CanvasSlide[] = [
  // Hook slide
  {
    id: 'arc-slide-1',
    backgroundColor: '#18181b',
    elements: [
      {
        id: 'arc-1-tag',
        type: 'text',
        x: 80,
        y: 100,
        width: 300,
        height: 30,
        rotation: 0,
        text: 'A PERSONAL STORY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#a78bfa',
        align: 'left',
        letterSpacing: 3,
      },
      {
        id: 'arc-1-hook',
        type: 'text',
        x: 80,
        y: 300,
        width: 920,
        height: 220,
        rotation: 0,
        text: 'I was fired on\na Monday.\nBy Friday, everything\nchanged.',
        fontSize: 52,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'arc-1-arrow',
        type: 'text',
        x: 80,
        y: 920,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'Read my story >>',
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#71717a',
        align: 'center',
      },
    ],
  },
  // Setup slide
  {
    id: 'arc-slide-2',
    backgroundColor: '#18181b',
    elements: [
      {
        id: 'arc-2-label',
        type: 'shape',
        x: 80,
        y: 80,
        width: 120,
        height: 36,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a78bfa',
        cornerRadius: 18,
      },
      {
        id: 'arc-2-label-text',
        type: 'text',
        x: 80,
        y: 85,
        width: 120,
        height: 28,
        rotation: 0,
        text: 'THE SETUP',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#18181b',
        align: 'center',
        letterSpacing: 1,
      },
      {
        id: 'arc-2-content',
        type: 'text',
        x: 80,
        y: 200,
        width: 920,
        height: 500,
        rotation: 0,
        text: 'I had been at the company for 3 years.\n\nI thought I was safe.\nI thought I was valued.\nI thought wrong.\n\nThe meeting lasted 12 minutes.\nThat was all it took to undo\neverything I had built.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e4e4e7',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  // Conflict slide
  {
    id: 'arc-slide-3',
    backgroundColor: '#18181b',
    elements: [
      {
        id: 'arc-3-label',
        type: 'shape',
        x: 80,
        y: 80,
        width: 140,
        height: 36,
        rotation: 0,
        shapeType: 'rect',
        fill: '#f87171',
        cornerRadius: 18,
      },
      {
        id: 'arc-3-label-text',
        type: 'text',
        x: 80,
        y: 85,
        width: 140,
        height: 28,
        rotation: 0,
        text: 'THE CONFLICT',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#18181b',
        align: 'center',
        letterSpacing: 1,
      },
      {
        id: 'arc-3-content',
        type: 'text',
        x: 80,
        y: 200,
        width: 920,
        height: 500,
        rotation: 0,
        text: 'The first 48 hours were the hardest.\n\nSelf-doubt hit like a wave.\nFear followed close behind.\nI questioned everything.\n\nBut somewhere in the darkness,\nI found a spark of clarity.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e4e4e7',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  // Turning point slide
  {
    id: 'arc-slide-4',
    backgroundColor: '#18181b',
    elements: [
      {
        id: 'arc-4-label',
        type: 'shape',
        x: 80,
        y: 80,
        width: 170,
        height: 36,
        rotation: 0,
        shapeType: 'rect',
        fill: '#fbbf24',
        cornerRadius: 18,
      },
      {
        id: 'arc-4-label-text',
        type: 'text',
        x: 80,
        y: 85,
        width: 170,
        height: 28,
        rotation: 0,
        text: 'TURNING POINT',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#18181b',
        align: 'center',
        letterSpacing: 1,
      },
      {
        id: 'arc-4-content',
        type: 'text',
        x: 80,
        y: 200,
        width: 920,
        height: 500,
        rotation: 0,
        text: 'On Wednesday, I made a decision:\n\nInstead of finding a new job,\nI would create one.\n\nI reached out to 50 people.\nI offered to solve real problems.\nI stopped waiting for permission.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e4e4e7',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  // Resolution slide
  {
    id: 'arc-slide-5',
    backgroundColor: '#18181b',
    elements: [
      {
        id: 'arc-5-label',
        type: 'shape',
        x: 80,
        y: 80,
        width: 160,
        height: 36,
        rotation: 0,
        shapeType: 'rect',
        fill: '#34d399',
        cornerRadius: 18,
      },
      {
        id: 'arc-5-label-text',
        type: 'text',
        x: 80,
        y: 85,
        width: 160,
        height: 28,
        rotation: 0,
        text: 'THE LESSON',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#18181b',
        align: 'center',
        letterSpacing: 1,
      },
      {
        id: 'arc-5-content',
        type: 'text',
        x: 80,
        y: 200,
        width: 920,
        height: 500,
        rotation: 0,
        text: 'By Friday, I had my first client.\n\n3 lessons from that week:\n\n1. Your job is not your identity\n2. Adversity reveals character\n3. The best time to start is now\n\nSometimes the worst day of your\nlife becomes the best thing\nthat ever happened to you.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e4e4e7',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  // CTA slide
  {
    id: 'arc-slide-6',
    backgroundColor: '#a78bfa',
    elements: [
      {
        id: 'arc-6-title',
        type: 'text',
        x: 80,
        y: 340,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'Your story\nisn\'t over.',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#18181b',
        align: 'center',
        lineHeight: 1.1,
      },
      {
        id: 'arc-6-subtitle',
        type: 'text',
        x: 80,
        y: 510,
        width: 920,
        height: 50,
        rotation: 0,
        text: 'Share yours in the comments.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#2e1065',
        align: 'center',
      },
      {
        id: 'arc-6-follow',
        type: 'text',
        x: 80,
        y: 620,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'Follow @yourhandle for more',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: '600',
        fill: '#18181b',
        align: 'center',
      },
    ],
  },
];

/**
 * Story Arc template configuration
 */
export const storyArcTemplate: CanvasTemplate = {
  id: 'default-story-arc',
  name: 'Story Arc',
  description: 'Hook, setup, conflict, turning point, lesson, and CTA. A complete narrative framework.',
  category: 'bold',
  brandColors: ['#18181b', '#a78bfa', '#f87171', '#fbbf24', '#34d399'],
  fonts: ['Inter'],
  defaultSlides: storyArcSlides,
  isFavorite: false,
};
