/**
 * Financial Tips Template
 * Black and green modern design for entrepreneur content
 * Inspired by the modern LinkedIn carousel aesthetic
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * Financial Tips template slides with black/green modern styling
 * Features: Grid background effect, green accent cards, bold typography
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Cover/Title Slide
  {
    id: 'fin-slide-1',
    backgroundColor: '#1a1a1a',
    elements: [
      // Grid pattern simulation - vertical lines
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-1-grid-v-${i}`,
        type: 'shape' as const,
        x: 90 * i,
        y: 0,
        width: 1,
        height: 1080,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Grid pattern simulation - horizontal lines
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-1-grid-h-${i}`,
        type: 'shape' as const,
        x: 0,
        y: 90 * i,
        width: 1080,
        height: 1,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Header - Author Name (left)
      {
        id: 'fin-1-author',
        type: 'text',
        x: 60,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'Your Name',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      // Header - Handle (right)
      {
        id: 'fin-1-handle',
        type: 'text',
        x: 620,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: '@yourhandle',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
      // White border/shadow effect (offset rectangle)
      {
        id: 'fin-1-card-border',
        type: 'shape',
        x: 95,
        y: 145,
        width: 890,
        height: 540,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#ffffff',
        strokeWidth: 2,
        cornerRadius: 24,
      },
      // Main green card
      {
        id: 'fin-1-card',
        type: 'shape',
        x: 80,
        y: 130,
        width: 890,
        height: 540,
        rotation: 0,
        shapeType: 'rect',
        fill: '#4ade80',
        cornerRadius: 24,
      },
      // Main title - "FINANCIAL"
      {
        id: 'fin-1-title-1',
        type: 'text',
        x: 100,
        y: 220,
        width: 850,
        height: 120,
        rotation: 0,
        text: 'FINANCIAL',
        fontSize: 100,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#000000',
        align: 'left',
      },
      // Main title - "TIPS FOR"
      {
        id: 'fin-1-title-2',
        type: 'text',
        x: 100,
        y: 340,
        width: 600,
        height: 120,
        rotation: 0,
        text: 'TIPS FOR',
        fontSize: 100,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#000000',
        align: 'left',
      },
      // Document icon placeholder (using text)
      {
        id: 'fin-1-icon',
        type: 'text',
        x: 700,
        y: 340,
        width: 150,
        height: 120,
        rotation: 0,
        text: '📄',
        fontSize: 80,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#000000',
        align: 'center',
      },
      // Subtitle container border
      {
        id: 'fin-1-subtitle-border',
        type: 'shape',
        x: 95,
        y: 685,
        width: 890,
        height: 100,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#ffffff',
        strokeWidth: 2,
        cornerRadius: 16,
      },
      // Subtitle - "ENTREPRENEURS"
      {
        id: 'fin-1-subtitle',
        type: 'text',
        x: 80,
        y: 700,
        width: 920,
        height: 70,
        rotation: 0,
        text: 'ENTREPRENEURS',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: '300',
        fontStyle: 'italic',
        fill: '#ffffff',
        align: 'center',
        letterSpacing: 8,
      },
      // Footer - Website URL
      {
        id: 'fin-1-url',
        type: 'text',
        x: 60,
        y: 980,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'yourwebsite.com',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'left',
      },
      // Footer - Swipe arrow
      {
        id: 'fin-1-arrow',
        type: 'text',
        x: 700,
        y: 980,
        width: 320,
        height: 40,
        rotation: 0,
        text: '————→',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
    ],
  },
  // Slide 2: Tip #1 - Understanding Cash Flow
  {
    id: 'fin-slide-2',
    backgroundColor: '#1a1a1a',
    elements: [
      // Grid pattern - vertical
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-2-grid-v-${i}`,
        type: 'shape' as const,
        x: 90 * i,
        y: 0,
        width: 1,
        height: 1080,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Grid pattern - horizontal
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-2-grid-h-${i}`,
        type: 'shape' as const,
        x: 0,
        y: 90 * i,
        width: 1080,
        height: 1,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Header - Author Name
      {
        id: 'fin-2-author',
        type: 'text',
        x: 60,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'Your Name',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      // Header - Handle
      {
        id: 'fin-2-handle',
        type: 'text',
        x: 620,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: '@yourhandle',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
      // White border effect
      {
        id: 'fin-2-card-border',
        type: 'shape',
        x: 95,
        y: 130,
        width: 890,
        height: 720,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#ffffff',
        strokeWidth: 2,
        cornerRadius: 24,
      },
      // Main green card
      {
        id: 'fin-2-card',
        type: 'shape',
        x: 80,
        y: 115,
        width: 890,
        height: 720,
        rotation: 0,
        shapeType: 'rect',
        fill: '#4ade80',
        cornerRadius: 24,
      },
      // Number circle
      {
        id: 'fin-2-number-circle',
        type: 'shape',
        x: 120,
        y: 180,
        width: 100,
        height: 100,
        rotation: 0,
        shapeType: 'circle',
        fill: 'transparent',
        stroke: '#000000',
        strokeWidth: 3,
      },
      // Number text
      {
        id: 'fin-2-number',
        type: 'text',
        x: 120,
        y: 195,
        width: 100,
        height: 70,
        rotation: 0,
        text: '01',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fontStyle: 'italic',
        fill: '#000000',
        align: 'center',
      },
      // Title
      {
        id: 'fin-2-title',
        type: 'text',
        x: 250,
        y: 180,
        width: 680,
        height: 140,
        rotation: 0,
        text: 'UNDERSTANDING\nCASH FLOW',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#000000',
        align: 'left',
        lineHeight: 1.1,
      },
      // Content
      {
        id: 'fin-2-content',
        type: 'text',
        x: 120,
        y: 400,
        width: 820,
        height: 380,
        rotation: 0,
        text: 'Cash flow—the heartbeat of your business! Monitoring your incoming and outgoing finances is crucial for maintaining a healthy financial state. Track your revenue, expenses, and timing to avoid surprises and make informed decisions.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#000000',
        align: 'left',
        lineHeight: 1.6,
      },
      // Footer - Website URL
      {
        id: 'fin-2-url',
        type: 'text',
        x: 60,
        y: 980,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'yourwebsite.com',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'left',
      },
      // Footer - Swipe arrow
      {
        id: 'fin-2-arrow',
        type: 'text',
        x: 700,
        y: 980,
        width: 320,
        height: 40,
        rotation: 0,
        text: '————→',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
    ],
  },
  // Slide 3: Tip #2 - Tax Planning Matters
  {
    id: 'fin-slide-3',
    backgroundColor: '#1a1a1a',
    elements: [
      // Grid pattern - vertical
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-3-grid-v-${i}`,
        type: 'shape' as const,
        x: 90 * i,
        y: 0,
        width: 1,
        height: 1080,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Grid pattern - horizontal
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-3-grid-h-${i}`,
        type: 'shape' as const,
        x: 0,
        y: 90 * i,
        width: 1080,
        height: 1,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Header - Author Name
      {
        id: 'fin-3-author',
        type: 'text',
        x: 60,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'Your Name',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      // Header - Handle
      {
        id: 'fin-3-handle',
        type: 'text',
        x: 620,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: '@yourhandle',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
      // White border effect
      {
        id: 'fin-3-card-border',
        type: 'shape',
        x: 95,
        y: 130,
        width: 890,
        height: 720,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#ffffff',
        strokeWidth: 2,
        cornerRadius: 24,
      },
      // Main green card
      {
        id: 'fin-3-card',
        type: 'shape',
        x: 80,
        y: 115,
        width: 890,
        height: 720,
        rotation: 0,
        shapeType: 'rect',
        fill: '#4ade80',
        cornerRadius: 24,
      },
      // Title (left side)
      {
        id: 'fin-3-title',
        type: 'text',
        x: 120,
        y: 200,
        width: 580,
        height: 180,
        rotation: 0,
        text: 'TAX PLANNING\nMATTERS',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#000000',
        align: 'left',
        lineHeight: 1.1,
      },
      // Number circle (right side)
      {
        id: 'fin-3-number-circle',
        type: 'shape',
        x: 780,
        y: 200,
        width: 100,
        height: 100,
        rotation: 0,
        shapeType: 'circle',
        fill: 'transparent',
        stroke: '#000000',
        strokeWidth: 3,
      },
      // Number text
      {
        id: 'fin-3-number',
        type: 'text',
        x: 780,
        y: 215,
        width: 100,
        height: 70,
        rotation: 0,
        text: '02',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fontStyle: 'italic',
        fill: '#000000',
        align: 'center',
      },
      // Content
      {
        id: 'fin-3-content',
        type: 'text',
        x: 120,
        y: 450,
        width: 820,
        height: 320,
        rotation: 0,
        text: 'Stay on top of tax regulations! Proper tax planning saves money and prevents last-minute stress during tax season. Work with experts to optimize your tax strategy and ensure compliance.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#000000',
        align: 'left',
        lineHeight: 1.6,
      },
      // Footer - Website URL
      {
        id: 'fin-3-url',
        type: 'text',
        x: 60,
        y: 980,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'yourwebsite.com',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'left',
      },
      // Footer - Swipe arrow
      {
        id: 'fin-3-arrow',
        type: 'text',
        x: 700,
        y: 980,
        width: 320,
        height: 40,
        rotation: 0,
        text: '————→',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
    ],
  },
  // Slide 4: Tip #3 - Secure Your Future
  {
    id: 'fin-slide-4',
    backgroundColor: '#1a1a1a',
    elements: [
      // Grid pattern - vertical
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-4-grid-v-${i}`,
        type: 'shape' as const,
        x: 90 * i,
        y: 0,
        width: 1,
        height: 1080,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Grid pattern - horizontal
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-4-grid-h-${i}`,
        type: 'shape' as const,
        x: 0,
        y: 90 * i,
        width: 1080,
        height: 1,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Header - Author Name
      {
        id: 'fin-4-author',
        type: 'text',
        x: 60,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'Your Name',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      // Header - Handle
      {
        id: 'fin-4-handle',
        type: 'text',
        x: 620,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: '@yourhandle',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
      // White border effect
      {
        id: 'fin-4-card-border',
        type: 'shape',
        x: 95,
        y: 130,
        width: 890,
        height: 720,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#ffffff',
        strokeWidth: 2,
        cornerRadius: 24,
      },
      // Main green card
      {
        id: 'fin-4-card',
        type: 'shape',
        x: 80,
        y: 115,
        width: 890,
        height: 720,
        rotation: 0,
        shapeType: 'rect',
        fill: '#4ade80',
        cornerRadius: 24,
      },
      // Number circle (left side)
      {
        id: 'fin-4-number-circle',
        type: 'shape',
        x: 120,
        y: 180,
        width: 100,
        height: 100,
        rotation: 0,
        shapeType: 'circle',
        fill: 'transparent',
        stroke: '#000000',
        strokeWidth: 3,
      },
      // Number text
      {
        id: 'fin-4-number',
        type: 'text',
        x: 120,
        y: 195,
        width: 100,
        height: 70,
        rotation: 0,
        text: '03',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fontStyle: 'italic',
        fill: '#000000',
        align: 'center',
      },
      // Title
      {
        id: 'fin-4-title',
        type: 'text',
        x: 250,
        y: 180,
        width: 680,
        height: 140,
        rotation: 0,
        text: 'SECURE YOUR\nFUTURE',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#000000',
        align: 'left',
        lineHeight: 1.1,
      },
      // Content
      {
        id: 'fin-4-content',
        type: 'text',
        x: 120,
        y: 400,
        width: 820,
        height: 380,
        rotation: 0,
        text: "Don't forget personal financial planning! Secure your future by setting up retirement funds and protecting your family with adequate insurance coverage. A solid foundation ensures peace of mind.",
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#000000',
        align: 'left',
        lineHeight: 1.6,
      },
      // Footer - Website URL
      {
        id: 'fin-4-url',
        type: 'text',
        x: 60,
        y: 980,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'yourwebsite.com',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'left',
      },
      // Footer - Swipe arrow
      {
        id: 'fin-4-arrow',
        type: 'text',
        x: 700,
        y: 980,
        width: 320,
        height: 40,
        rotation: 0,
        text: '————→',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
    ],
  },
  // Slide 5: CTA - Was This Helpful?
  {
    id: 'fin-slide-5',
    backgroundColor: '#1a1a1a',
    elements: [
      // Grid pattern - vertical
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-5-grid-v-${i}`,
        type: 'shape' as const,
        x: 90 * i,
        y: 0,
        width: 1,
        height: 1080,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Grid pattern - horizontal
      ...Array.from({ length: 12 }, (_, i) => ({
        id: `fin-5-grid-h-${i}`,
        type: 'shape' as const,
        x: 0,
        y: 90 * i,
        width: 1080,
        height: 1,
        rotation: 0,
        shapeType: 'rect' as const,
        fill: '#2a2a2a',
      })),
      // Header - Author Name
      {
        id: 'fin-5-author',
        type: 'text',
        x: 60,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: 'Your Name',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      // Header - Handle
      {
        id: 'fin-5-handle',
        type: 'text',
        x: 620,
        y: 50,
        width: 400,
        height: 40,
        rotation: 0,
        text: '@yourhandle',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'right',
      },
      // White border effect
      {
        id: 'fin-5-card-border',
        type: 'shape',
        x: 95,
        y: 145,
        width: 890,
        height: 540,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#ffffff',
        strokeWidth: 2,
        cornerRadius: 24,
      },
      // Main green card
      {
        id: 'fin-5-card',
        type: 'shape',
        x: 80,
        y: 130,
        width: 890,
        height: 540,
        rotation: 0,
        shapeType: 'rect',
        fill: '#4ade80',
        cornerRadius: 24,
      },
      // Main CTA text - "WAS THIS"
      {
        id: 'fin-5-cta-1',
        type: 'text',
        x: 100,
        y: 250,
        width: 850,
        height: 120,
        rotation: 0,
        text: 'WAS THIS',
        fontSize: 100,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#000000',
        align: 'center',
      },
      // Main CTA text - "HELPFUL?"
      {
        id: 'fin-5-cta-2',
        type: 'text',
        x: 100,
        y: 370,
        width: 850,
        height: 120,
        rotation: 0,
        text: 'HELPFUL?',
        fontSize: 100,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#000000',
        align: 'center',
      },
      // Save this post container border
      {
        id: 'fin-5-save-border',
        type: 'shape',
        x: 95,
        y: 700,
        width: 890,
        height: 100,
        rotation: 0,
        shapeType: 'rect',
        fill: 'transparent',
        stroke: '#ffffff',
        strokeWidth: 2,
        cornerRadius: 16,
      },
      // Save this post text
      {
        id: 'fin-5-save-text',
        type: 'text',
        x: 200,
        y: 720,
        width: 500,
        height: 60,
        rotation: 0,
        text: 'SAVE THIS POST',
        fontSize: 40,
        fontFamily: 'Inter',
        fontWeight: '300',
        fontStyle: 'italic',
        fill: '#ffffff',
        align: 'center',
        letterSpacing: 4,
      },
      // Bookmark icon
      {
        id: 'fin-5-bookmark',
        type: 'text',
        x: 720,
        y: 710,
        width: 80,
        height: 80,
        rotation: 0,
        text: '🔖',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#fbbf24',
        align: 'center',
      },
      // Footer - Website URL (centered)
      {
        id: 'fin-5-url',
        type: 'text',
        x: 80,
        y: 980,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'yourwebsite.com',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
];

/**
 * Financial Tips template configuration
 * Black and green modern design for entrepreneur content
 */
export const financialTipsTemplate: CanvasTemplate = {
  id: 'financial-tips-1',
  name: 'Financial Tips for Entrepreneurs',
  description: 'Modern black and green design perfect for financial advice, business tips, and entrepreneur content',
  category: 'bold',
  brandColors: ['#1a1a1a', '#4ade80', '#ffffff', '#000000', '#fbbf24'],
  fonts: ['Inter'],
  defaultSlides,
};
