/**
 * Minimal Template
 * Clean, elegant design with lots of whitespace and refined typography
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * Minimal template slides with elegant, simple styling
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Title Slide
  {
    id: 'minimal-slide-1',
    backgroundColor: '#fafaf9',
    elements: [
      {
        id: 'minimal-1-line',
        type: 'shape',
        x: 490,
        y: 200,
        width: 100,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 1,
      },
      {
        id: 'minimal-1-title',
        type: 'text',
        x: 80,
        y: 380,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'The Art of\nSimplicity',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#1c1917',
        align: 'center',
        lineHeight: 1.2,
      },
      {
        id: 'minimal-1-subtitle',
        type: 'text',
        x: 80,
        y: 560,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Less is more in design and in life',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#78716c',
        align: 'center',
      },
      {
        id: 'minimal-1-line2',
        type: 'shape',
        x: 490,
        y: 880,
        width: 100,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 1,
      },
    ],
  },
  // Slide 2: Quote
  {
    id: 'minimal-slide-2',
    backgroundColor: '#1c1917',
    elements: [
      {
        id: 'minimal-2-quote',
        type: 'text',
        x: 80,
        y: 80,
        width: 120,
        height: 150,
        rotation: 0,
        text: '\u201C',
        fontSize: 200,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#57534e',
        align: 'left',
      },
      {
        id: 'minimal-2-content',
        type: 'text',
        x: 120,
        y: 340,
        width: 840,
        height: 250,
        rotation: 0,
        text: 'Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#fafaf9',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'minimal-2-author',
        type: 'text',
        x: 120,
        y: 650,
        width: 840,
        height: 40,
        rotation: 0,
        text: '— Antoine de Saint-Exupéry',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#78716c',
        align: 'left',
      },
    ],
  },
  // Slide 3: Point 1
  {
    id: 'minimal-slide-3',
    backgroundColor: '#fafaf9',
    elements: [
      {
        id: 'minimal-3-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 100,
        height: 80,
        rotation: 0,
        text: '01',
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#a8a29e',
        align: 'left',
      },
      {
        id: 'minimal-3-line',
        type: 'shape',
        x: 80,
        y: 150,
        width: 40,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 1,
      },
      {
        id: 'minimal-3-title',
        type: 'text',
        x: 80,
        y: 200,
        width: 600,
        height: 160,
        rotation: 0,
        text: 'Remove the unnecessary',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#1c1917',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'minimal-3-content',
        type: 'text',
        x: 80,
        y: 420,
        width: 700,
        height: 200,
        rotation: 0,
        text: 'Every element should serve a purpose. If it doesn\'t add value, it\'s taking away from the experience.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  // Slide 4: Point 2
  {
    id: 'minimal-slide-4',
    backgroundColor: '#fafaf9',
    elements: [
      {
        id: 'minimal-4-number',
        type: 'text',
        x: 80,
        y: 80,
        width: 100,
        height: 80,
        rotation: 0,
        text: '02',
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#a8a29e',
        align: 'left',
      },
      {
        id: 'minimal-4-line',
        type: 'shape',
        x: 80,
        y: 150,
        width: 40,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 1,
      },
      {
        id: 'minimal-4-title',
        type: 'text',
        x: 80,
        y: 200,
        width: 600,
        height: 160,
        rotation: 0,
        text: 'Embrace whitespace',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#1c1917',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'minimal-4-content',
        type: 'text',
        x: 80,
        y: 420,
        width: 700,
        height: 200,
        rotation: 0,
        text: 'Empty space isn\'t wasted space. It gives your content room to breathe and your ideas room to shine.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
    ],
  },
  // Slide 5: Closing
  {
    id: 'minimal-slide-5',
    backgroundColor: '#1c1917',
    elements: [
      {
        id: 'minimal-5-line',
        type: 'shape',
        x: 490,
        y: 300,
        width: 100,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#57534e',
        cornerRadius: 1,
      },
      {
        id: 'minimal-5-title',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Keep it simple.',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#fafaf9',
        align: 'center',
      },
      {
        id: 'minimal-5-subtitle',
        type: 'text',
        x: 80,
        y: 520,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Follow for more minimal insights',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#78716c',
        align: 'center',
      },
      {
        id: 'minimal-5-line2',
        type: 'shape',
        x: 490,
        y: 750,
        width: 100,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#57534e',
        cornerRadius: 1,
      },
    ],
  },
];

/**
 * Minimal template configuration
 */
export const minimalTemplate: CanvasTemplate = {
  id: 'minimal-1',
  name: 'Elegant Minimal',
  description: 'Sophisticated design with refined typography and generous whitespace',
  category: 'minimal',
  brandColors: ['#1c1917', '#fafaf9', '#78716c', '#a8a29e', '#57534e'],
  fonts: ['Inter'],
  defaultSlides,
};
