/**
 * Minimal Template
 * Clean, elegant design with lots of whitespace and refined typography
 * Enhanced with subtle geometric accents that maintain the minimalist aesthetic
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * Minimal template slides with elegant, simple styling and geometric accents
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Title Slide
  {
    id: 'minimal-slide-1',
    backgroundColor: '#fafaf9',
    elements: [
      // Subtle corner accent (top-right) - thin L-shape formed by two rects
      {
        id: 'minimal-1-corner-h',
        type: 'shape',
        x: 920,
        y: 60,
        width: 100,
        height: 1,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
      },
      {
        id: 'minimal-1-corner-v',
        type: 'shape',
        x: 1020,
        y: 60,
        width: 1,
        height: 100,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
      },
      // Bottom-left corner accent
      {
        id: 'minimal-1-corner2-h',
        type: 'shape',
        x: 60,
        y: 1020,
        width: 100,
        height: 1,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
      },
      {
        id: 'minimal-1-corner2-v',
        type: 'shape',
        x: 60,
        y: 920,
        width: 1,
        height: 100,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
      },
      // Small circle as period/accent
      {
        id: 'minimal-1-dot',
        type: 'shape',
        x: 534,
        y: 320,
        width: 12,
        height: 12,
        rotation: 0,
        shapeType: 'circle',
        fill: '#a8a29e',
      },
      {
        id: 'minimal-1-line',
        type: 'shape',
        x: 490,
        y: 200,
        width: 100,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 1,
      },
      {
        id: 'minimal-1-title',
        type: 'text',
        x: 80,
        y: 380,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'The Art of\nSimplicity',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#1c1917',
        align: 'center',
        lineHeight: 1.2,
      },
      {
        id: 'minimal-1-subtitle',
        type: 'text',
        x: 80,
        y: 560,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Less is more in design and in life',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#78716c',
        align: 'center',
      },
      {
        id: 'minimal-1-line2',
        type: 'shape',
        x: 490,
        y: 880,
        width: 100,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 1,
      },
    ],
  },
  // Slide 2: Quote
  {
    id: 'minimal-slide-2',
    backgroundColor: '#1c1917',
    elements: [
      // Subtle large circle in background (very low opacity)
      {
        id: 'minimal-2-deco-circle',
        type: 'shape',
        x: 600,
        y: -100,
        width: 700,
        height: 700,
        rotation: 0,
        shapeType: 'circle',
        fill: '#29231f',
      },
      // Thin vertical accent line (left)
      {
        id: 'minimal-2-deco-line',
        type: 'shape',
        x: 80,
        y: 280,
        width: 1,
        height: 400,
        rotation: 0,
        shapeType: 'rect',
        fill: '#44403c',
      },
      {
        id: 'minimal-2-quote',
        type: 'text',
        x: 80,
        y: 80,
        width: 120,
        height: 150,
        rotation: 0,
        text: '\u201C',
        fontSize: 200,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#57534e',
        align: 'left',
      },
      {
        id: 'minimal-2-content',
        type: 'text',
        x: 120,
        y: 340,
        width: 840,
        height: 250,
        rotation: 0,
        text: 'Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#fafaf9',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'minimal-2-author',
        type: 'text',
        x: 120,
        y: 650,
        width: 840,
        height: 40,
        rotation: 0,
        text: '\u2014 Antoine de Saint-Exup\u00e9ry',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#78716c',
        align: 'left',
      },
      // Small accent dot
      {
        id: 'minimal-2-deco-dot',
        type: 'shape',
        x: 120,
        y: 720,
        width: 6,
        height: 6,
        rotation: 0,
        shapeType: 'circle',
        fill: '#57534e',
      },
    ],
  },
  // Slide 3: Point 1
  {
    id: 'minimal-slide-3',
    backgroundColor: '#fafaf9',
    elements: [
      // Subtle large circle (right side, barely visible)
      {
        id: 'minimal-3-deco-circle',
        type: 'shape',
        x: 700,
        y: 200,
        width: 500,
        height: 500,
        rotation: 0,
        shapeType: 'circle',
        fill: '#f5f5f4',
      },
      // Small bullet circle
      {
        id: 'minimal-3-bullet',
        type: 'shape',
        x: 80,
        y: 105,
        width: 8,
        height: 8,
        rotation: 0,
        shapeType: 'circle',
        fill: '#1c1917',
      },
      {
        id: 'minimal-3-number',
        type: 'text',
        x: 100,
        y: 80,
        width: 100,
        height: 80,
        rotation: 0,
        text: '01',
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#a8a29e',
        align: 'left',
      },
      {
        id: 'minimal-3-line',
        type: 'shape',
        x: 80,
        y: 150,
        width: 40,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 1,
      },
      {
        id: 'minimal-3-title',
        type: 'text',
        x: 80,
        y: 200,
        width: 600,
        height: 160,
        rotation: 0,
        text: 'Remove the unnecessary',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#1c1917',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'minimal-3-content',
        type: 'text',
        x: 80,
        y: 420,
        width: 700,
        height: 200,
        rotation: 0,
        text: 'Every element should serve a purpose. If it doesn\'t add value, it\'s taking away from the experience.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
      // Bottom accent - thin cross pattern
      {
        id: 'minimal-3-deco-h',
        type: 'shape',
        x: 950,
        y: 950,
        width: 30,
        height: 1,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
      },
      {
        id: 'minimal-3-deco-v',
        type: 'shape',
        x: 965,
        y: 935,
        width: 1,
        height: 30,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
      },
    ],
  },
  // Slide 4: Point 2
  {
    id: 'minimal-slide-4',
    backgroundColor: '#fafaf9',
    elements: [
      // Thin horizontal rule (decorative)
      {
        id: 'minimal-4-deco-rule',
        type: 'shape',
        x: 80,
        y: 800,
        width: 920,
        height: 1,
        rotation: 0,
        shapeType: 'rect',
        fill: '#e7e5e4',
      },
      // Small bullet circle
      {
        id: 'minimal-4-bullet',
        type: 'shape',
        x: 80,
        y: 105,
        width: 8,
        height: 8,
        rotation: 0,
        shapeType: 'circle',
        fill: '#1c1917',
      },
      {
        id: 'minimal-4-number',
        type: 'text',
        x: 100,
        y: 80,
        width: 100,
        height: 80,
        rotation: 0,
        text: '02',
        fontSize: 18,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#a8a29e',
        align: 'left',
      },
      {
        id: 'minimal-4-line',
        type: 'shape',
        x: 80,
        y: 150,
        width: 40,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 1,
      },
      {
        id: 'minimal-4-title',
        type: 'text',
        x: 80,
        y: 200,
        width: 600,
        height: 160,
        rotation: 0,
        text: 'Embrace whitespace',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#1c1917',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'minimal-4-content',
        type: 'text',
        x: 80,
        y: 420,
        width: 700,
        height: 200,
        rotation: 0,
        text: 'Empty space isn\'t wasted space. It gives your content room to breathe and your ideas room to shine.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
      // Decorative small squares
      {
        id: 'minimal-4-deco-sq1',
        type: 'shape',
        x: 940,
        y: 80,
        width: 12,
        height: 12,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
        cornerRadius: 2,
      },
      {
        id: 'minimal-4-deco-sq2',
        type: 'shape',
        x: 960,
        y: 80,
        width: 12,
        height: 12,
        rotation: 0,
        shapeType: 'rect',
        fill: '#e7e5e4',
        cornerRadius: 2,
      },
    ],
  },
  // Slide 5: Closing
  {
    id: 'minimal-slide-5',
    backgroundColor: '#1c1917',
    elements: [
      // Subtle large circle (center, barely visible)
      {
        id: 'minimal-5-deco-circle',
        type: 'shape',
        x: 290,
        y: 290,
        width: 500,
        height: 500,
        rotation: 0,
        shapeType: 'circle',
        fill: '#29231f',
      },
      // Corner accents (matching slide 1 but inverted)
      {
        id: 'minimal-5-corner-h',
        type: 'shape',
        x: 60,
        y: 60,
        width: 100,
        height: 1,
        rotation: 0,
        shapeType: 'rect',
        fill: '#44403c',
      },
      {
        id: 'minimal-5-corner-v',
        type: 'shape',
        x: 60,
        y: 60,
        width: 1,
        height: 100,
        rotation: 0,
        shapeType: 'rect',
        fill: '#44403c',
      },
      {
        id: 'minimal-5-line',
        type: 'shape',
        x: 490,
        y: 300,
        width: 100,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#57534e',
        cornerRadius: 1,
      },
      {
        id: 'minimal-5-title',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Keep it simple.',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '300',
        fill: '#fafaf9',
        align: 'center',
      },
      {
        id: 'minimal-5-subtitle',
        type: 'text',
        x: 80,
        y: 520,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Follow for more minimal insights',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#78716c',
        align: 'center',
      },
      {
        id: 'minimal-5-line2',
        type: 'shape',
        x: 490,
        y: 750,
        width: 100,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#57534e',
        cornerRadius: 1,
      },
      // Bottom-right corner accent
      {
        id: 'minimal-5-corner2-h',
        type: 'shape',
        x: 920,
        y: 1020,
        width: 100,
        height: 1,
        rotation: 0,
        shapeType: 'rect',
        fill: '#44403c',
      },
      {
        id: 'minimal-5-corner2-v',
        type: 'shape',
        x: 1020,
        y: 920,
        width: 1,
        height: 100,
        rotation: 0,
        shapeType: 'rect',
        fill: '#44403c',
      },
    ],
  },
];

/**
 * Minimal template configuration
 */
export const minimalTemplate: CanvasTemplate = {
  id: 'minimal-1',
  name: 'Elegant Minimal',
  description: 'Sophisticated design with refined typography and generous whitespace',
  category: 'minimal',
  brandColors: ['#1c1917', '#fafaf9', '#78716c', '#a8a29e', '#57534e'],
  fonts: ['Inter'],
  defaultTone: 'professional',
  defaultSlides,
};
