/**
 * Professional Template
 * Clean business style with navy and blue accent colors
 * Enhanced with decorative geometric shapes for visual depth
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * Professional template slides with corporate styling and decorative elements
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Title Slide
  {
    id: 'prof-slide-1',
    backgroundColor: '#1e3a5f',
    elements: [
      // Large decorative circle (top-right, partially off-canvas)
      {
        id: 'prof-1-deco-circle1',
        type: 'shape',
        x: 700,
        y: -200,
        width: 600,
        height: 600,
        rotation: 0,
        shapeType: 'circle',
        fill: '#264a73',
      },
      // Subtle rotated rectangle accent (bottom-left)
      {
        id: 'prof-1-deco-rect1',
        type: 'shape',
        x: -200,
        y: 700,
        width: 500,
        height: 500,
        rotation: 45,
        shapeType: 'rect',
        fill: '#243f63',
        cornerRadius: 30,
      },
      // Small accent circle cluster (top-left)
      {
        id: 'prof-1-deco-dot1',
        type: 'shape',
        x: 80,
        y: 80,
        width: 14,
        height: 14,
        rotation: 0,
        shapeType: 'circle',
        fill: '#3b82f6',
      },
      {
        id: 'prof-1-deco-dot2',
        type: 'shape',
        x: 104,
        y: 80,
        width: 10,
        height: 10,
        rotation: 0,
        shapeType: 'circle',
        fill: '#3b82f680',
      },
      {
        id: 'prof-1-deco-dot3',
        type: 'shape',
        x: 122,
        y: 80,
        width: 6,
        height: 6,
        rotation: 0,
        shapeType: 'circle',
        fill: '#3b82f640',
      },
      // Horizontal accent bar
      {
        id: 'prof-1-deco-bar',
        type: 'shape',
        x: 390,
        y: 340,
        width: 300,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 2,
      },
      {
        id: 'prof-1-title',
        type: 'text',
        x: 80,
        y: 380,
        width: 920,
        height: 100,
        rotation: 0,
        text: '5 Key Insights',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'prof-1-subtitle',
        type: 'text',
        x: 80,
        y: 500,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'That Changed My Career',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#94a3b8',
        align: 'center',
      },
      {
        id: 'prof-1-author',
        type: 'text',
        x: 80,
        y: 900,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'By Your Name',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#64748b',
        align: 'center',
      },
    ],
  },
  // Slide 2: First Point
  {
    id: 'prof-slide-2',
    backgroundColor: '#ffffff',
    elements: [
      // Top-right decorative circle (partially off-canvas)
      {
        id: 'prof-2-deco-circle',
        type: 'shape',
        x: 850,
        y: -80,
        width: 350,
        height: 350,
        rotation: 0,
        shapeType: 'circle',
        fill: '#3b82f610',
      },
      // Left vertical accent bar
      {
        id: 'prof-2-deco-sidebar',
        type: 'shape',
        x: 0,
        y: 0,
        width: 6,
        height: 1080,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
      },
      // Number background circle
      {
        id: 'prof-2-num-bg',
        type: 'shape',
        x: 60,
        y: 90,
        width: 130,
        height: 130,
        rotation: 0,
        shapeType: 'circle',
        fill: '#eff6ff',
      },
      {
        id: 'prof-2-number',
        type: 'text',
        x: 65,
        y: 105,
        width: 120,
        height: 120,
        rotation: 0,
        text: '01',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#3b82f6',
        align: 'center',
      },
      {
        id: 'prof-2-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'First Key Insight',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e3a5f',
        align: 'left',
      },
      {
        id: 'prof-2-content',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Explain your first insight here. Keep it concise and impactful. Use simple language that resonates with your audience.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'prof-2-accent',
        type: 'shape',
        x: 80,
        y: 680,
        width: 100,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 2,
      },
      // Bottom-left accent dots
      {
        id: 'prof-2-deco-dot1',
        type: 'shape',
        x: 80,
        y: 950,
        width: 8,
        height: 8,
        rotation: 0,
        shapeType: 'circle',
        fill: '#3b82f6',
      },
      {
        id: 'prof-2-deco-dot2',
        type: 'shape',
        x: 98,
        y: 950,
        width: 8,
        height: 8,
        rotation: 0,
        shapeType: 'circle',
        fill: '#3b82f660',
      },
      {
        id: 'prof-2-deco-dot3',
        type: 'shape',
        x: 116,
        y: 950,
        width: 8,
        height: 8,
        rotation: 0,
        shapeType: 'circle',
        fill: '#3b82f630',
      },
    ],
  },
  // Slide 3: Second Point
  {
    id: 'prof-slide-3',
    backgroundColor: '#ffffff',
    elements: [
      // Decorative rotated rect (bottom-right corner)
      {
        id: 'prof-3-deco-rect',
        type: 'shape',
        x: 800,
        y: 800,
        width: 400,
        height: 400,
        rotation: 45,
        shapeType: 'rect',
        fill: '#1e3a5f08',
        cornerRadius: 20,
      },
      // Left vertical accent bar
      {
        id: 'prof-3-deco-sidebar',
        type: 'shape',
        x: 0,
        y: 0,
        width: 6,
        height: 1080,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
      },
      // Number background circle
      {
        id: 'prof-3-num-bg',
        type: 'shape',
        x: 60,
        y: 90,
        width: 130,
        height: 130,
        rotation: 0,
        shapeType: 'circle',
        fill: '#eff6ff',
      },
      {
        id: 'prof-3-number',
        type: 'text',
        x: 65,
        y: 105,
        width: 120,
        height: 120,
        rotation: 0,
        text: '02',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#3b82f6',
        align: 'center',
      },
      {
        id: 'prof-3-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'Second Key Insight',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e3a5f',
        align: 'left',
      },
      {
        id: 'prof-3-content',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Share your second insight with supporting details. Make it actionable so readers can apply it immediately.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'prof-3-accent',
        type: 'shape',
        x: 80,
        y: 680,
        width: 100,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 2,
      },
      // Right-side decorative thin line
      {
        id: 'prof-3-deco-line',
        type: 'shape',
        x: 1000,
        y: 200,
        width: 2,
        height: 300,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f620',
        cornerRadius: 1,
      },
    ],
  },
  // Slide 4: Third Point
  {
    id: 'prof-slide-4',
    backgroundColor: '#ffffff',
    elements: [
      // Large subtle circle (center-left, behind content)
      {
        id: 'prof-4-deco-circle',
        type: 'shape',
        x: -100,
        y: 300,
        width: 500,
        height: 500,
        rotation: 0,
        shapeType: 'circle',
        fill: '#3b82f608',
      },
      // Left vertical accent bar
      {
        id: 'prof-4-deco-sidebar',
        type: 'shape',
        x: 0,
        y: 0,
        width: 6,
        height: 1080,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
      },
      // Number background circle
      {
        id: 'prof-4-num-bg',
        type: 'shape',
        x: 60,
        y: 90,
        width: 130,
        height: 130,
        rotation: 0,
        shapeType: 'circle',
        fill: '#eff6ff',
      },
      {
        id: 'prof-4-number',
        type: 'text',
        x: 65,
        y: 105,
        width: 120,
        height: 120,
        rotation: 0,
        text: '03',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#3b82f6',
        align: 'center',
      },
      {
        id: 'prof-4-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'Third Key Insight',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e3a5f',
        align: 'left',
      },
      {
        id: 'prof-4-content',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Continue building on your message. Each slide should flow naturally into the next.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'prof-4-accent',
        type: 'shape',
        x: 80,
        y: 680,
        width: 100,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 2,
      },
      // Two small accent squares (bottom-right)
      {
        id: 'prof-4-deco-sq1',
        type: 'shape',
        x: 950,
        y: 920,
        width: 20,
        height: 20,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 4,
      },
      {
        id: 'prof-4-deco-sq2',
        type: 'shape',
        x: 980,
        y: 950,
        width: 14,
        height: 14,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f640',
        cornerRadius: 3,
      },
    ],
  },
  // Slide 5: CTA/Closing
  {
    id: 'prof-slide-5',
    backgroundColor: '#1e3a5f',
    elements: [
      // Large decorative circle (bottom-right, partially off-canvas)
      {
        id: 'prof-5-deco-circle1',
        type: 'shape',
        x: 700,
        y: 650,
        width: 600,
        height: 600,
        rotation: 0,
        shapeType: 'circle',
        fill: '#264a73',
      },
      // Top-left decorative circle
      {
        id: 'prof-5-deco-circle2',
        type: 'shape',
        x: -150,
        y: -150,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: '#243f63',
      },
      // Accent bar above title
      {
        id: 'prof-5-deco-bar',
        type: 'shape',
        x: 440,
        y: 300,
        width: 200,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 2,
      },
      // Star emoji as visual element
      {
        id: 'prof-5-emoji',
        type: 'text',
        x: 470,
        y: 200,
        width: 140,
        height: 100,
        rotation: 0,
        text: '\u2728',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'prof-5-title',
        type: 'text',
        x: 80,
        y: 340,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Ready to Transform?',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'prof-5-cta',
        type: 'text',
        x: 80,
        y: 480,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Follow for more insights \u2192',
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#3b82f6',
        align: 'center',
      },
      {
        id: 'prof-5-handle',
        type: 'text',
        x: 80,
        y: 900,
        width: 920,
        height: 40,
        rotation: 0,
        text: '@yourhandle',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#64748b',
        align: 'center',
      },
    ],
  },
];

/**
 * Professional template configuration
 */
export const professionalTemplate: CanvasTemplate = {
  id: 'professional-1',
  name: 'Corporate Insights',
  description: 'Clean and professional design perfect for business content and thought leadership',
  category: 'professional',
  brandColors: ['#1e3a5f', '#3b82f6', '#ffffff', '#94a3b8', '#475569'],
  fonts: ['Inter'],
  defaultTone: 'professional',
  defaultSlides,
};
