/**
 * Professional Template
 * Clean business style with navy and blue accent colors
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * Professional template slides with corporate styling
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Title Slide
  {
    id: 'prof-slide-1',
    backgroundColor: '#1e3a5f',
    elements: [
      {
        id: 'prof-1-title',
        type: 'text',
        x: 80,
        y: 380,
        width: 920,
        height: 100,
        rotation: 0,
        text: '5 Key Insights',
        fontSize: 72,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'prof-1-subtitle',
        type: 'text',
        x: 80,
        y: 500,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'That Changed My Career',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#94a3b8',
        align: 'center',
      },
      {
        id: 'prof-1-author',
        type: 'text',
        x: 80,
        y: 900,
        width: 920,
        height: 40,
        rotation: 0,
        text: 'By Your Name',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#64748b',
        align: 'center',
      },
    ],
  },
  // Slide 2: First Point
  {
    id: 'prof-slide-2',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'prof-2-number',
        type: 'text',
        x: 80,
        y: 100,
        width: 120,
        height: 120,
        rotation: 0,
        text: '01',
        fontSize: 96,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#3b82f6',
        align: 'left',
      },
      {
        id: 'prof-2-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'First Key Insight',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e3a5f',
        align: 'left',
      },
      {
        id: 'prof-2-content',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Explain your first insight here. Keep it concise and impactful. Use simple language that resonates with your audience.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'prof-2-accent',
        type: 'shape',
        x: 80,
        y: 680,
        width: 100,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 2,
      },
    ],
  },
  // Slide 3: Second Point
  {
    id: 'prof-slide-3',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'prof-3-number',
        type: 'text',
        x: 80,
        y: 100,
        width: 120,
        height: 120,
        rotation: 0,
        text: '02',
        fontSize: 96,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#3b82f6',
        align: 'left',
      },
      {
        id: 'prof-3-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'Second Key Insight',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e3a5f',
        align: 'left',
      },
      {
        id: 'prof-3-content',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Share your second insight with supporting details. Make it actionable so readers can apply it immediately.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'prof-3-accent',
        type: 'shape',
        x: 80,
        y: 680,
        width: 100,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 2,
      },
    ],
  },
  // Slide 4: Third Point
  {
    id: 'prof-slide-4',
    backgroundColor: '#ffffff',
    elements: [
      {
        id: 'prof-4-number',
        type: 'text',
        x: 80,
        y: 100,
        width: 120,
        height: 120,
        rotation: 0,
        text: '03',
        fontSize: 96,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#3b82f6',
        align: 'left',
      },
      {
        id: 'prof-4-title',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'Third Key Insight',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#1e3a5f',
        align: 'left',
      },
      {
        id: 'prof-4-content',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'Continue building on your message. Each slide should flow naturally into the next.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#475569',
        align: 'left',
        lineHeight: 1.5,
      },
      {
        id: 'prof-4-accent',
        type: 'shape',
        x: 80,
        y: 680,
        width: 100,
        height: 4,
        rotation: 0,
        shapeType: 'rect',
        fill: '#3b82f6',
        cornerRadius: 2,
      },
    ],
  },
  // Slide 5: CTA/Closing
  {
    id: 'prof-slide-5',
    backgroundColor: '#1e3a5f',
    elements: [
      {
        id: 'prof-5-title',
        type: 'text',
        x: 80,
        y: 340,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Ready to Transform?',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'prof-5-cta',
        type: 'text',
        x: 80,
        y: 480,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Follow for more insights \u2192',
        fontSize: 32,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#3b82f6',
        align: 'center',
      },
      {
        id: 'prof-5-handle',
        type: 'text',
        x: 80,
        y: 900,
        width: 920,
        height: 40,
        rotation: 0,
        text: '@yourhandle',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#64748b',
        align: 'center',
      },
    ],
  },
];

/**
 * Professional template configuration
 */
export const professionalTemplate: CanvasTemplate = {
  id: 'professional-1',
  name: 'Corporate Insights',
  description: 'Clean and professional design perfect for business content and thought leadership',
  category: 'professional',
  brandColors: ['#1e3a5f', '#3b82f6', '#ffffff', '#94a3b8', '#475569'],
  fonts: ['Inter'],
  defaultSlides,
};
