/**
 * Story Template
 * Narrative flow style for storytelling carousels
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * Story template slides with narrative progression
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Hook
  {
    id: 'story-slide-1',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'story-1-gradient',
        type: 'shape',
        x: 0,
        y: 600,
        width: 1080,
        height: 480,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1e293b',
        cornerRadius: 0,
      },
      {
        id: 'story-1-year',
        type: 'text',
        x: 80,
        y: 150,
        width: 200,
        height: 50,
        rotation: 0,
        text: '2024',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#3b82f6',
        align: 'left',
      },
      {
        id: 'story-1-title',
        type: 'text',
        x: 80,
        y: 260,
        width: 920,
        height: 200,
        rotation: 0,
        text: 'I Lost Everything.\nHere\'s What I Learned.',
        fontSize: 56,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
        lineHeight: 1.2,
      },
      {
        id: 'story-1-subtitle',
        type: 'text',
        x: 80,
        y: 500,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'A thread about failure, resilience, and growth',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#94a3b8',
        align: 'left',
      },
      {
        id: 'story-1-cta',
        type: 'text',
        x: 80,
        y: 900,
        width: 920,
        height: 40,
        rotation: 0,
        text: '\u{1F9F5} Thread \u2192',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#64748b',
        align: 'center',
      },
    ],
  },
  // Slide 2: The Beginning
  {
    id: 'story-slide-2',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'story-2-chapter',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 40,
        rotation: 0,
        text: 'Chapter 1',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#3b82f6',
        align: 'left',
      },
      {
        id: 'story-2-title',
        type: 'text',
        x: 80,
        y: 150,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'The Beginning',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'story-2-content',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 400,
        rotation: 0,
        text: 'Two years ago, I was on top of the world.\n\nI had:\n\u2022 A thriving business\n\u2022 A growing team\n\u2022 Unlimited confidence\n\nThen everything changed...',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e2e8f0',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'story-2-line',
        type: 'shape',
        x: 80,
        y: 900,
        width: 920,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#334155',
        cornerRadius: 1,
      },
    ],
  },
  // Slide 3: The Problem
  {
    id: 'story-slide-3',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'story-3-chapter',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 40,
        rotation: 0,
        text: 'Chapter 2',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ef4444',
        align: 'left',
      },
      {
        id: 'story-3-title',
        type: 'text',
        x: 80,
        y: 150,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'The Fall',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'story-3-content',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 400,
        rotation: 0,
        text: 'In one month, I lost:\n\n\u274C 80% of my revenue\n\u274C My biggest client\n\u274C Half my team\n\nI had two choices:\n\nGive up or adapt.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e2e8f0',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'story-3-line',
        type: 'shape',
        x: 80,
        y: 900,
        width: 920,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#334155',
        cornerRadius: 1,
      },
    ],
  },
  // Slide 4: The Lesson
  {
    id: 'story-slide-4',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'story-4-chapter',
        type: 'text',
        x: 80,
        y: 80,
        width: 200,
        height: 40,
        rotation: 0,
        text: 'Chapter 3',
        fontSize: 16,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#10b981',
        align: 'left',
      },
      {
        id: 'story-4-title',
        type: 'text',
        x: 80,
        y: 150,
        width: 920,
        height: 80,
        rotation: 0,
        text: 'The Lesson',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'left',
      },
      {
        id: 'story-4-content',
        type: 'text',
        x: 80,
        y: 280,
        width: 920,
        height: 400,
        rotation: 0,
        text: 'Here\'s what failure taught me:\n\n\u2705 Diversify your income\n\u2705 Build relationships, not transactions\n\u2705 Save for the unexpected\n\u2705 Stay humble, stay hungry\n\nThe comeback is always stronger than the setback.',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#e2e8f0',
        align: 'left',
        lineHeight: 1.6,
      },
      {
        id: 'story-4-line',
        type: 'shape',
        x: 80,
        y: 900,
        width: 920,
        height: 2,
        rotation: 0,
        shapeType: 'rect',
        fill: '#334155',
        cornerRadius: 1,
      },
    ],
  },
  // Slide 5: The Resolution
  {
    id: 'story-slide-5',
    backgroundColor: '#0f172a',
    elements: [
      {
        id: 'story-5-gradient',
        type: 'shape',
        x: 0,
        y: 0,
        width: 1080,
        height: 480,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1e293b',
        cornerRadius: 0,
      },
      {
        id: 'story-5-emoji',
        type: 'text',
        x: 440,
        y: 200,
        width: 200,
        height: 150,
        rotation: 0,
        text: '\u{1F4AA}',
        fontSize: 100,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'story-5-title',
        type: 'text',
        x: 80,
        y: 400,
        width: 920,
        height: 100,
        rotation: 0,
        text: 'Today, I\'m stronger.',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      {
        id: 'story-5-subtitle',
        type: 'text',
        x: 80,
        y: 520,
        width: 920,
        height: 120,
        rotation: 0,
        text: 'If you\'re going through something similar,\nremember: this too shall pass.',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#94a3b8',
        align: 'center',
        lineHeight: 1.5,
      },
      {
        id: 'story-5-cta',
        type: 'text',
        x: 80,
        y: 750,
        width: 920,
        height: 60,
        rotation: 0,
        text: 'Follow for more real stories \u{1F499}',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#3b82f6',
        align: 'center',
      },
    ],
  },
];

/**
 * Story template configuration
 */
export const storyTemplate: CanvasTemplate = {
  id: 'story-1',
  name: 'Story Thread',
  description: 'Narrative-driven design for compelling storytelling and personal experiences',
  category: 'bold',
  brandColors: ['#0f172a', '#1e293b', '#3b82f6', '#ef4444', '#10b981'],
  fonts: ['Inter'],
  defaultSlides,
};
