/**
 * White Minimal Time Management Tips Template
 * Clean beige/cream design with black typography and subtle accents
 * Features: Numbered tips, decorative arc, navigation elements
 * Enhanced with clock/time-themed decorative shapes and elegant accents
 */

import type { CanvasTemplate, CanvasSlide } from '@/types/canvas-editor';

/**
 * White Minimal Time Management template slides
 * Based on the Canva "White Minimal Time Management Tips LinkedIn Carousel" design
 */
const defaultSlides: CanvasSlide[] = [
  // Slide 1: Cover/Title Slide
  {
    id: 'wmt-slide-1',
    backgroundColor: '#f5f0e8',
    elements: [
      // Top-left label - "PRODUCTIVITY"
      {
        id: 'wmt-1-label-left',
        type: 'text',
        x: 60,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'PRODUCTIVITY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Top-right label - "LIFE TIPS"
      {
        id: 'wmt-1-label-right',
        type: 'text',
        x: 820,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'LIFE TIPS',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'right',
        letterSpacing: 2,
        textDecoration: 'underline',
      },
      // Clock-like concentric circles (decorative)
      {
        id: 'wmt-1-clock-outer',
        type: 'shape',
        x: 680,
        y: 100,
        width: 400,
        height: 400,
        rotation: 0,
        shapeType: 'circle',
        fill: 'transparent',
        stroke: '#d6d3d1',
        strokeWidth: 1,
      },
      {
        id: 'wmt-1-clock-inner',
        type: 'shape',
        x: 730,
        y: 150,
        width: 300,
        height: 300,
        rotation: 0,
        shapeType: 'circle',
        fill: 'transparent',
        stroke: '#e7e5e4',
        strokeWidth: 1,
      },
      // Clock hand (simulated with thin rect)
      {
        id: 'wmt-1-clock-hand',
        type: 'shape',
        x: 878,
        y: 200,
        width: 2,
        height: 100,
        rotation: 30,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 1,
      },
      // Clock center dot
      {
        id: 'wmt-1-clock-center',
        type: 'shape',
        x: 873,
        y: 293,
        width: 8,
        height: 8,
        rotation: 0,
        shapeType: 'circle',
        fill: '#1c1917',
      },
      // Hourglass emoji
      {
        id: 'wmt-1-deco-emoji',
        type: 'text',
        x: 60,
        y: 200,
        width: 100,
        height: 100,
        rotation: 0,
        text: '\u231B',
        fontSize: 60,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'center',
      },
      // Decorative arc (approximated with line)
      {
        id: 'wmt-1-arc',
        type: 'shape',
        x: 700,
        y: 150,
        width: 400,
        height: 600,
        rotation: 0,
        shapeType: 'circle',
        fill: 'transparent',
        stroke: '#57534e',
        strokeWidth: 1,
      },
      // Main title - "5 WAYS TO"
      {
        id: 'wmt-1-title-1',
        type: 'text',
        x: 60,
        y: 480,
        width: 600,
        height: 80,
        rotation: 0,
        text: '5 WAYS TO',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
      },
      // Main title - "MANAGE TIME"
      {
        id: 'wmt-1-title-2',
        type: 'text',
        x: 60,
        y: 550,
        width: 700,
        height: 80,
        rotation: 0,
        text: 'MANAGE TIME',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
      },
      // Main title - "EFFECTIVELY"
      {
        id: 'wmt-1-title-3',
        type: 'text',
        x: 60,
        y: 620,
        width: 700,
        height: 80,
        rotation: 0,
        text: 'EFFECTIVELY',
        fontSize: 64,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
      },
      // Author
      {
        id: 'wmt-1-author',
        type: 'text',
        x: 60,
        y: 730,
        width: 400,
        height: 30,
        rotation: 0,
        text: 'BY NEIL TRAN',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: '500',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Bottom-left - "TRY THIS OUT"
      {
        id: 'wmt-1-cta',
        type: 'text',
        x: 60,
        y: 980,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TRY THIS OUT',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 1,
      },
      // Bottom-right - Arrow button background
      {
        id: 'wmt-1-arrow-bg',
        type: 'shape',
        x: 960,
        y: 960,
        width: 60,
        height: 60,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 12,
      },
      // Arrow icon
      {
        id: 'wmt-1-arrow',
        type: 'text',
        x: 960,
        y: 965,
        width: 60,
        height: 50,
        rotation: 0,
        text: '→',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 2: Tip #1 - Prioritize and Schedule Work
  {
    id: 'wmt-slide-2',
    backgroundColor: '#f5f0e8',
    elements: [
      // Top-left label
      {
        id: 'wmt-2-label-left',
        type: 'text',
        x: 60,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'PRODUCTIVITY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Top-right label
      {
        id: 'wmt-2-label-right',
        type: 'text',
        x: 820,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'LIFE TIPS',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'right',
        letterSpacing: 2,
        textDecoration: 'underline',
      },
      // Subtle circle accent (right side)
      {
        id: 'wmt-2-deco-circle',
        type: 'shape',
        x: 800,
        y: 150,
        width: 350,
        height: 350,
        rotation: 0,
        shapeType: 'circle',
        fill: '#ece8e0',
      },
      // Thin vertical accent line
      {
        id: 'wmt-2-deco-line',
        type: 'shape',
        x: 40,
        y: 360,
        width: 2,
        height: 300,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
        cornerRadius: 1,
      },
      // Number badge background
      {
        id: 'wmt-2-number-bg',
        type: 'shape',
        x: 60,
        y: 380,
        width: 50,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 8,
      },
      // Number
      {
        id: 'wmt-2-number',
        type: 'text',
        x: 60,
        y: 385,
        width: 50,
        height: 40,
        rotation: 0,
        text: '01',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      // Title
      {
        id: 'wmt-2-title',
        type: 'text',
        x: 130,
        y: 360,
        width: 700,
        height: 140,
        rotation: 0,
        text: 'PRIORITIZE\nAND SCHEDULE\nWORK',
        fontSize: 48,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
        lineHeight: 1.1,
      },
      // Description
      {
        id: 'wmt-2-desc',
        type: 'text',
        x: 130,
        y: 550,
        width: 700,
        height: 150,
        rotation: 0,
        text: 'Get used to doing important work first.\nThat way, your time will be organized\neffectively and efficiently.',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
      // Bottom-left CTA
      {
        id: 'wmt-2-cta',
        type: 'text',
        x: 60,
        y: 980,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TRY THIS OUT',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 1,
      },
      // Arrow button background
      {
        id: 'wmt-2-arrow-bg',
        type: 'shape',
        x: 960,
        y: 960,
        width: 60,
        height: 60,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 12,
      },
      // Arrow icon
      {
        id: 'wmt-2-arrow',
        type: 'text',
        x: 960,
        y: 965,
        width: 60,
        height: 50,
        rotation: 0,
        text: '→',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 3: Tip #2 - Stay Focused
  {
    id: 'wmt-slide-3',
    backgroundColor: '#f5f0e8',
    elements: [
      // Top-left label
      {
        id: 'wmt-3-label-left',
        type: 'text',
        x: 60,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'PRODUCTIVITY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Top-right label
      {
        id: 'wmt-3-label-right',
        type: 'text',
        x: 820,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'LIFE TIPS',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'right',
        letterSpacing: 2,
        textDecoration: 'underline',
      },
      // Subtle rotated rect accent
      {
        id: 'wmt-3-deco-rect',
        type: 'shape',
        x: 800,
        y: 600,
        width: 300,
        height: 300,
        rotation: 45,
        shapeType: 'rect',
        fill: '#ece8e0',
        cornerRadius: 20,
      },
      // Number badge background
      {
        id: 'wmt-3-number-bg',
        type: 'shape',
        x: 60,
        y: 380,
        width: 50,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 8,
      },
      // Number
      {
        id: 'wmt-3-number',
        type: 'text',
        x: 60,
        y: 385,
        width: 50,
        height: 40,
        rotation: 0,
        text: '02',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      // Title
      {
        id: 'wmt-3-title',
        type: 'text',
        x: 130,
        y: 380,
        width: 700,
        height: 80,
        rotation: 0,
        text: 'STAY FOCUSED',
        fontSize: 52,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
      },
      // Description
      {
        id: 'wmt-3-desc',
        type: 'text',
        x: 130,
        y: 480,
        width: 700,
        height: 180,
        rotation: 0,
        text: 'You will agree that focus is the main\nkey. Even though you are busy with\nmany tasks, try to stay focused. That\nway, your tasks will be completed\nproperly and more quickly.',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
      // Bottom-left CTA
      {
        id: 'wmt-3-cta',
        type: 'text',
        x: 60,
        y: 980,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TRY THIS OUT',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 1,
      },
      // Arrow button
      {
        id: 'wmt-3-arrow-bg',
        type: 'shape',
        x: 960,
        y: 960,
        width: 60,
        height: 60,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 12,
      },
      {
        id: 'wmt-3-arrow',
        type: 'text',
        x: 960,
        y: 965,
        width: 60,
        height: 50,
        rotation: 0,
        text: '→',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 4: Tip #3 - Time Discipline
  {
    id: 'wmt-slide-4',
    backgroundColor: '#f5f0e8',
    elements: [
      // Top-left label
      {
        id: 'wmt-4-label-left',
        type: 'text',
        x: 60,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'PRODUCTIVITY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Top-right label
      {
        id: 'wmt-4-label-right',
        type: 'text',
        x: 820,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'LIFE TIPS',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'right',
        letterSpacing: 2,
        textDecoration: 'underline',
      },
      // Subtle circle (left side, different position)
      {
        id: 'wmt-4-deco-circle',
        type: 'shape',
        x: -100,
        y: 600,
        width: 300,
        height: 300,
        rotation: 0,
        shapeType: 'circle',
        fill: '#ece8e0',
      },
      // Decorative dots (right side)
      {
        id: 'wmt-4-deco-dot1',
        type: 'shape',
        x: 900,
        y: 400,
        width: 6,
        height: 6,
        rotation: 0,
        shapeType: 'circle',
        fill: '#a8a29e',
      },
      {
        id: 'wmt-4-deco-dot2',
        type: 'shape',
        x: 920,
        y: 400,
        width: 6,
        height: 6,
        rotation: 0,
        shapeType: 'circle',
        fill: '#a8a29e60',
      },
      // Number badge background
      {
        id: 'wmt-4-number-bg',
        type: 'shape',
        x: 60,
        y: 380,
        width: 50,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 8,
      },
      // Number
      {
        id: 'wmt-4-number',
        type: 'text',
        x: 60,
        y: 385,
        width: 50,
        height: 40,
        rotation: 0,
        text: '03',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      // Title
      {
        id: 'wmt-4-title',
        type: 'text',
        x: 130,
        y: 380,
        width: 700,
        height: 80,
        rotation: 0,
        text: 'TIME DISCIPLINE',
        fontSize: 52,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
      },
      // Description
      {
        id: 'wmt-4-desc',
        type: 'text',
        x: 130,
        y: 480,
        width: 700,
        height: 180,
        rotation: 0,
        text: 'Try to be disciplined with the time you\nhave and avoid procrastinating on\nwork. An undisciplined attitude makes\nwork pile up and delays its\ncompletion.',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
      // Bottom-left CTA
      {
        id: 'wmt-4-cta',
        type: 'text',
        x: 60,
        y: 980,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TRY THIS OUT',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 1,
      },
      // Arrow button
      {
        id: 'wmt-4-arrow-bg',
        type: 'shape',
        x: 960,
        y: 960,
        width: 60,
        height: 60,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 12,
      },
      {
        id: 'wmt-4-arrow',
        type: 'text',
        x: 960,
        y: 965,
        width: 60,
        height: 50,
        rotation: 0,
        text: '→',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 5: Tip #4 - Don't Overthink
  {
    id: 'wmt-slide-5',
    backgroundColor: '#f5f0e8',
    elements: [
      // Top-left label
      {
        id: 'wmt-5-label-left',
        type: 'text',
        x: 60,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'PRODUCTIVITY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Top-right label
      {
        id: 'wmt-5-label-right',
        type: 'text',
        x: 820,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'LIFE TIPS',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'right',
        letterSpacing: 2,
        textDecoration: 'underline',
      },
      // Decorative circle (top-right)
      {
        id: 'wmt-5-deco-circle',
        type: 'shape',
        x: 850,
        y: -50,
        width: 300,
        height: 300,
        rotation: 0,
        shapeType: 'circle',
        fill: '#ece8e0',
      },
      // Number badge background
      {
        id: 'wmt-5-number-bg',
        type: 'shape',
        x: 60,
        y: 380,
        width: 50,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 8,
      },
      // Number
      {
        id: 'wmt-5-number',
        type: 'text',
        x: 60,
        y: 385,
        width: 50,
        height: 40,
        rotation: 0,
        text: '04',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      // Title
      {
        id: 'wmt-5-title',
        type: 'text',
        x: 130,
        y: 360,
        width: 700,
        height: 120,
        rotation: 0,
        text: "DON'T\nOVERTHINK",
        fontSize: 52,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
        lineHeight: 1.1,
      },
      // Description
      {
        id: 'wmt-5-desc',
        type: 'text',
        x: 130,
        y: 510,
        width: 700,
        height: 150,
        rotation: 0,
        text: 'Overthinking and planning without\nrealistic steps are akin to wasting\ntime. Start taking action to complete\nyour work.',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
      // Bottom-left CTA
      {
        id: 'wmt-5-cta',
        type: 'text',
        x: 60,
        y: 980,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TRY THIS OUT',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 1,
      },
      // Arrow button
      {
        id: 'wmt-5-arrow-bg',
        type: 'shape',
        x: 960,
        y: 960,
        width: 60,
        height: 60,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 12,
      },
      {
        id: 'wmt-5-arrow',
        type: 'text',
        x: 960,
        y: 965,
        width: 60,
        height: 50,
        rotation: 0,
        text: '→',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 6: Tip #5 - Stay Healthy
  {
    id: 'wmt-slide-6',
    backgroundColor: '#f5f0e8',
    elements: [
      // Top-left label
      {
        id: 'wmt-6-label-left',
        type: 'text',
        x: 60,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'PRODUCTIVITY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Top-right label
      {
        id: 'wmt-6-label-right',
        type: 'text',
        x: 820,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'LIFE TIPS',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'right',
        letterSpacing: 2,
        textDecoration: 'underline',
      },
      // Decorative rotated rectangle
      {
        id: 'wmt-6-deco-rect',
        type: 'shape',
        x: -100,
        y: -100,
        width: 300,
        height: 300,
        rotation: 45,
        shapeType: 'rect',
        fill: '#ece8e0',
        cornerRadius: 20,
      },
      // Health emoji
      {
        id: 'wmt-6-deco-emoji',
        type: 'text',
        x: 900,
        y: 380,
        width: 80,
        height: 80,
        rotation: 0,
        text: '\u{1F33F}',
        fontSize: 40,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'center',
      },
      // Number badge background
      {
        id: 'wmt-6-number-bg',
        type: 'shape',
        x: 60,
        y: 380,
        width: 50,
        height: 50,
        rotation: 0,
        shapeType: 'rect',
        fill: '#1c1917',
        cornerRadius: 8,
      },
      // Number
      {
        id: 'wmt-6-number',
        type: 'text',
        x: 60,
        y: 385,
        width: 50,
        height: 40,
        rotation: 0,
        text: '05',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
      // Title
      {
        id: 'wmt-6-title',
        type: 'text',
        x: 130,
        y: 380,
        width: 700,
        height: 80,
        rotation: 0,
        text: 'STAY HEALTHY',
        fontSize: 52,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
      },
      // Description
      {
        id: 'wmt-6-desc',
        type: 'text',
        x: 130,
        y: 480,
        width: 700,
        height: 180,
        rotation: 0,
        text: 'Completing many tasks can be\nexhausting. Therefore, take\ncare of your health so you don\'t\nget sick easily and can\ncomplete all your work.',
        fontSize: 20,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#57534e',
        align: 'left',
        lineHeight: 1.6,
      },
      // Bottom-left CTA
      {
        id: 'wmt-6-cta',
        type: 'text',
        x: 60,
        y: 980,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'TRY THIS OUT',
        fontSize: 12,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 1,
      },
      // Arrow button
      {
        id: 'wmt-6-arrow-bg',
        type: 'shape',
        x: 960,
        y: 960,
        width: 60,
        height: 60,
        rotation: 0,
        shapeType: 'rect',
        fill: '#a8a29e',
        cornerRadius: 12,
      },
      {
        id: 'wmt-6-arrow',
        type: 'text',
        x: 960,
        y: 965,
        width: 60,
        height: 50,
        rotation: 0,
        text: '→',
        fontSize: 28,
        fontFamily: 'Inter',
        fontWeight: 'bold',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
  // Slide 7: CTA/Follow Slide
  {
    id: 'wmt-slide-7',
    backgroundColor: '#f5f0e8',
    elements: [
      // Top-left label
      {
        id: 'wmt-7-label-left',
        type: 'text',
        x: 60,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'PRODUCTIVITY',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Top-right label
      {
        id: 'wmt-7-label-right',
        type: 'text',
        x: 820,
        y: 50,
        width: 200,
        height: 30,
        rotation: 0,
        text: 'LIFE TIPS',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'right',
        letterSpacing: 2,
        textDecoration: 'underline',
      },
      // Large decorative circle (background)
      {
        id: 'wmt-7-deco-circle',
        type: 'shape',
        x: 600,
        y: -100,
        width: 600,
        height: 600,
        rotation: 0,
        shapeType: 'circle',
        fill: '#ece8e0',
      },
      // Thin line accent
      {
        id: 'wmt-7-deco-line',
        type: 'shape',
        x: 60,
        y: 300,
        width: 1,
        height: 200,
        rotation: 0,
        shapeType: 'rect',
        fill: '#d6d3d1',
      },
      // Heart icon
      {
        id: 'wmt-7-heart',
        type: 'text',
        x: 60,
        y: 380,
        width: 50,
        height: 50,
        rotation: 0,
        text: '♡',
        fontSize: 36,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#1c1917',
        align: 'center',
      },
      // CTA Title
      {
        id: 'wmt-7-title',
        type: 'text',
        x: 130,
        y: 340,
        width: 700,
        height: 200,
        rotation: 0,
        text: 'FOLLOW US\nTO GET MORE\nINFORMATION\nAND TIPS LIKE\nTHIS.',
        fontSize: 52,
        fontFamily: 'Inter',
        fontWeight: '900',
        fill: '#1c1917',
        align: 'left',
        lineHeight: 1.1,
      },
      // Handle
      {
        id: 'wmt-7-handle',
        type: 'text',
        x: 60,
        y: 920,
        width: 400,
        height: 30,
        rotation: 0,
        text: '@REALLYGREATSITE',
        fontSize: 14,
        fontFamily: 'Inter',
        fontWeight: '500',
        fill: '#1c1917',
        align: 'left',
        letterSpacing: 2,
      },
      // Bookmark button background
      {
        id: 'wmt-7-bookmark-bg',
        type: 'shape',
        x: 960,
        y: 960,
        width: 60,
        height: 60,
        rotation: 0,
        shapeType: 'rect',
        fill: '#78716c',
        cornerRadius: 12,
      },
      // Bookmark icon
      {
        id: 'wmt-7-bookmark',
        type: 'text',
        x: 960,
        y: 968,
        width: 60,
        height: 50,
        rotation: 0,
        text: '◻',
        fontSize: 24,
        fontFamily: 'Inter',
        fontWeight: 'normal',
        fill: '#ffffff',
        align: 'center',
      },
    ],
  },
];

/**
 * White Minimal Time Management Tips template configuration
 * Clean beige design perfect for productivity and life tips content
 */
export const whiteMinimalTimeManagementTemplate: CanvasTemplate = {
  id: 'white-minimal-time-management-1',
  name: 'White Minimal Time Management',
  description: 'Clean beige design with black typography, perfect for productivity tips and life advice carousels',
  category: 'minimal',
  brandColors: ['#f5f0e8', '#1c1917', '#57534e', '#a8a29e', '#78716c'],
  fonts: ['Inter'],
  defaultTone: 'educational',
  defaultSlides,
};
